-- Power unit element usage synced from FIA decision PDFs (see scripts/sync_fia_data.py).
-- Composite unique allows one row per driver per document URL. If you require a single
-- UNIQUE on fia_pdf_url only, store payloads as JSONB in a separate snapshot table instead.

CREATE TABLE IF NOT EXISTS public.fia_pu_elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fia_pdf_url TEXT NOT NULL,
    fia_doc_number INTEGER,
    is_revised BOOLEAN NOT NULL DEFAULT FALSE,
    driver_name TEXT NOT NULL,
    ice_count INTEGER,
    tc_count INTEGER,
    mguk_count INTEGER,
    es_count INTEGER,
    ce_count INTEGER,
    ex_count INTEGER,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fia_pu_elements_pdf_driver_unique UNIQUE (fia_pdf_url, driver_name)
);

CREATE INDEX IF NOT EXISTS fia_pu_elements_fia_pdf_url_idx
    ON public.fia_pu_elements (fia_pdf_url);

COMMENT ON TABLE public.fia_pu_elements IS
    'FIA "PU elements used per driver up to now" PDFs; upserted by sync_fia_data.py';
