/// Per-circuit Coach's Corner copy: five lines (track, strategy, weather, racecraft, session)
/// for each [Race.name] in [f1_data.dart], in en / nl / de / fr.
library;

/// Maps [Race.name] (exact string from `races`) to an internal slug.
const Map<String, String> kRaceNameToCoachSlug = {
  'Australian Grand Prix': 'australian',
  'Chinese Grand Prix': 'chinese',
  'Japanese Grand Prix': 'japanese',
  'Bahrain Grand Prix': 'bahrain',
  'Saudi Arabian Grand Prix': 'saudi_arabian',
  'Miami Grand Prix': 'miami',
  'Canadian Grand Prix': 'canadian',
  'Monaco Grand Prix': 'monaco',
  'Barcelona Grand Prix': 'barcelona',
  'Austrian Grand Prix': 'austrian',
  'British Grand Prix': 'british',
  'Belgian Grand Prix': 'belgian',
  'Hungarian Grand Prix': 'hungarian',
  'Dutch Grand Prix': 'dutch',
  'Italian Grand Prix': 'italian',
  'Spanish Grand Prix': 'spanish_madrid',
  'Azerbaijan Grand Prix': 'azerbaijan',
  'Singapore Grand Prix': 'singapore',
  'United States Grand Prix': 'united_states',
  'Mexico City Grand Prix': 'mexico_city',
  'São Paulo Grand Prix': 'sao_paulo',
  'Las Vegas Grand Prix': 'las_vegas',
  'Qatar Grand Prix': 'qatar',
  'Abu Dhabi Grand Prix': 'abu_dhabi',
};

String _languageKey(String languageCode) {
  switch (languageCode.toLowerCase()) {
    case 'nl':
      return 'nl';
    case 'de':
      return 'de';
    case 'fr':
      return 'fr';
    default:
      return 'en';
  }
}

/// Five coach lines for [raceName], localized. Unknown names use [fallback] strings.
List<String> coachCornerFiveLines(String raceName, String languageCode) {
  final slug = kRaceNameToCoachSlug[raceName] ?? 'fallback';
  final lang = _languageKey(languageCode);
  final bySlug = _kCoachByLocale[lang] ?? _kCoachByLocale['en']!;
  return List<String>.from(bySlug[slug] ?? bySlug['fallback']!);
}

const Map<String, Map<String, List<String>>> _kCoachByLocale = {
  'en': _coachEn,
  'nl': _coachNl,
  'de': _coachDe,
  'fr': _coachFr,
};

const Map<String, List<String>> _coachEn = {
  'fallback': [
    'Track: prioritise rhythm in sector 2 and protect the rears—this layout rewards clean exits.',
    'Strategy: flex between one and two stops after FP2 degradation runs; undercut threat is real.',
    'Weather: watch gusts on the longest straights and trim aero if crosswinds build.',
    'Racecraft: take the inside into the first big braking zone; the next straight punishes poor exits.',
    'Session plan: bank FP2 long runs first, then qualifying sims once the rubber is down.',
  ],
  'australian': [
    'Track: Turns 3–4 reward a tidy exit—Albert Park walls punish greedy throttle on the lakeside.',
    'Strategy: two-stop Medium/Hard splits are common; safety cars can flip the order—stay flexible.',
    'Weather: cool changeable air off the bay—grip can swing session to session.',
    'Racecraft: DRS along Lakeside Drive—set up the pass before the heavy braking into the stadium.',
    'Session plan: treat FP2 as the tyre reference; traffic on short laps makes clean long runs gold.',
  ],
  'chinese': [
    'Track: the “Snail” complex needs patience; the long back straight rewards a good traction exit.',
    'Strategy: sprint weekend—tyre allocation is tight; protect softs for SQ and race day.',
    'Weather: spring Shanghai can throw rain—watch spray on the long straight entries.',
    'Racecraft: Turn 1 is wide—defend inside but don’t compromise the run to the back straight.',
    'Session plan: sprint quali means fewer laps—nail track evolution between SQ and race.',
  ],
  'japanese': [
    'Track: 130R and the Esses reward rhythm—Suzuka is a flow circuit, not a point-and-squirt track.',
    'Strategy: one-stop Medium/Hard often wins; pit loss is painful—track position matters.',
    'Weather: autumn Honshu can be wet—intermediate timing around Degner is decisive.',
    'Racecraft: Casio Triangle is the overtaking lottery—brake late but leave room for cutback.',
    'Session plan: tyre warm-up on low-grip mornings—prioritise long runs in representative heat.',
  ],
  'bahrain': [
    'Track: traction out of the final corner sets up the main straight—rear stability is everything.',
    'Strategy: desert night race—two-stop is typical; watch undercuts when the field stacks.',
    'Weather: cool evenings but sand on track—front grip can vary lap to lap.',
    'Racecraft: Turns 1 and 4 are the main lunges—defend early, don’t drift wide onto traction paint.',
    'Session plan: FP2 mirrors race conditions—long runs under lights are your tyre baseline.',
  ],
  'saudi_arabian': [
    'Track: blind entries and concrete—commitment through the fast kinks is survival first.',
    'Strategy: high degradation—two stops common; safety car frequency can bunch the pack.',
    'Weather: coastal humidity at night—watch dew and changing rear grip.',
    'Racecraft: few clean spots to pass—set up at the chicanes, don’t force walls.',
    'Session plan: short practice—every lap counts; avoid traffic in quali sims.',
  ],
  'miami': [
    'Track: long corners and low grip off-line—stay disciplined; the marina section punishes mistakes.',
    'Strategy: heat and traction zones—two-stop window often opens if SC appears.',
    'Weather: Florida thunderstorms—radar matters; inter timing around the long straights.',
    'Racecraft: tight turns after long straights—brake in a straight line, avoid front-lock off-line.',
    'Session plan: track rubbers quickly—qualifying sims late Friday matter more than early banker.',
  ],
  'canadian': [
    'Track: Wall of Champions territory—last chicane needs precision; don’t chase kerbs too hard.',
    'Strategy: stop-go circuit—undercut on the long pit loss is powerful if traffic allows.',
    'Weather: variable Montreal summers—rain can arrive fast; grip on the hairpin changes.',
    'Racecraft: Hairpin and Senna S are the moves—brake late but protect the inside for the exit.',
    'Session plan: kerb evolution shifts balance—re-run quali trim after rubber builds.',
  ],
  'monaco': [
    'Track: no room for error—every corner is a qualifying lap; rhythm beats heroics.',
    'Strategy: track position > strategy—overcut rarely beats on-track order in the Principality.',
    'Weather: rare dry drama—if rain hits, the harbour section becomes ice on slicks.',
    'Racecraft: Tunnel exit and Nouvelle Chicane are ambush points—mirror defence early.',
    'Session plan: Thursday/Friday traffic jigsaw—find clear quali sims before Saturday matters.',
  ],
  'barcelona': [
    'Track: sector 3 traction onto the main straight decides tow battles—rear stability wins.',
    'Strategy: tyre wear on front-left—two-stop vs one-stop swings with track temp.',
    'Weather: Catalan wind across the grid—balance shifts corner to corner.',
    'Racecraft: Turn 1 and the final complex are the lunges—don’t compromise the run to Campsa.',
    'Session plan: representative heat in FP2—morning sand on track can mislead long-run reads.',
  ],
  'austrian': [
    'Track: short lap, big slipstream—qualifying tow games and race DRS trains are real.',
    'Strategy: soft tyre offset strategies appear—pit lane is short, undercuts sting.',
    'Weather: Alpine showers—local cells can drench sector 1 while sector 3 stays dry.',
    'Racecraft: Turns 3–4 and the final corner are dive zones—defend before the climb.',
    'Session plan: traffic on a 4.3 km lap—book clean quali laps early in the window.',
  ],
  'british': [
    'Track: high-speed balance—Copse, Maggots, Becketts reward commitment and a stable rear.',
    'Strategy: tyre blistering in heat—two-stop vs one-stop swings with asphalt temp.',
    'Weather: Silverstone wind and showers—full wets vs inters calls define weekends.',
    'Racecraft: Hangar Straight DRS duels—set the pass before Stowe, not through it.',
    'Session plan: Friday gusts vs Saturday calm—re-check aero balance before quali.',
  ],
  'belgian': [
    'Track: Eau Rouge–Raidillon needs respect—lift slightly if the rear is light; survival first.',
    'Strategy: long lap, big pit loss—undercut/ overcut chess; SC probability is high.',
    'Weather: Ardennes microclimate—one end of the track can be wet while the other is dry.',
    'Racecraft: Les Combes and Bus Stop are passing zones—brake straight, avoid kerb hop.',
    'Session plan: FP2 long runs in mixed conditions can lie—prioritise dry baseline if race dry.',
  ],
  'hungarian': [
    'Track: twisty Hungaroring—sector 2 rhythm is everything; protect fronts in long corners.',
    'Strategy: tough to overtake—qualifying matters; one-stop vs two-stop hinges on traffic.',
    'Weather: hot Budapest—rear overheating in traffic; watch thermal degradation.',
    'Racecraft: Turn 1 and chicane after the back straight—defend inside, don’t run wide.',
    'Session plan: low-speed balance shifts with fuel—run quali fuel levels in final practice.',
  ],
  'dutch': [
    'Track: banking and wind—Zandvoort is narrow; one mistake stacks a train behind you.',
    'Strategy: bank stoppers struggle in traffic—two-stop window if deg opens.',
    'Weather: North Sea gusts—coastal crosswinds into banking change balance lap to lap.',
    'Racecraft: Tarzan and Hans Ernst are lunges—late braking works if you keep rotation tight.',
    'Session plan: orange smoke limits vision in quali—pick a clear out-lap slot early.',
  ],
  'italian': [
    'Track: low drag, high speed—Monza is slipstream chess; tow in quali can decide rows.',
    'Strategy: one-stop vs two-stop swings with SC—pit lane is short, packs stay tight.',
    'Weather: late-summer storms—sudden rain on the straights while Lesmo stays dry.',
    'Racecraft: Rettifilo and della Roggia are the moves—brake late but don’t miss the apex.',
    'Session plan: track limits at Ascari and Parabolica—trim wing after FP1 baseline.',
  ],
  'spanish_madrid': [
    'Track: new hybrid layout—prioritise learning references; walls and surface grip are unknown early.',
    'Strategy: green track evolves fast—two-stop flexibility until deg numbers stabilise.',
    'Weather: Madrid heat and dust—grip can jump once the line rubbers in.',
    'Racecraft: unknown passing spots—protect the inside on long straights until maps settle.',
    'Session plan: every session is data—short-run vs long-run split to map tyre crossover.',
  ],
  'azerbaijan': [
    'Track: long straights into 90°—Baku punishes lockups; castle section is walls both sides.',
    'Strategy: SC likelihood—split strategies appear; pit entry speed trap catches mistakes.',
    'Weather: Caspian wind down the main straight—braking zones lengthen with headwind.',
    'Racecraft: Turn 1 and the castle chicane—dive early or don’t; no half moves.',
    'Session plan: FP1 street dust vs night race rubber—qualify on latest representative track.',
  ],
  'singapore': [
    'Track: bumpy street, 23 corners—mental load is high; front tyres take a beating.',
    'Strategy: two-hour race, high deg—two-stop baseline; safety cars bunch the field often.',
    'Weather: tropical storms—inter timing around the long straights decides podiums.',
    'Racecraft: few clean spots—set up at Raffles and the bay; avoid kerb hopping under brakes.',
    'Session plan: night heat vs evening quali—track evolution from FP2 to Q3 is huge.',
  ],
  'united_states': [
    'Track: esses through sector 1 need flow; rear stability sets up the long back straight.',
    'Strategy: tyre deg on traction zones—two-stop vs one-stop swings with asphalt temp.',
    'Weather: Texas gusts and heat—balance shifts; watch crosswind into the esses.',
    'Racecraft: Turn 1 and the back straight hairpin—late braking works if you keep rotation.',
    'Session plan: bumpy Austin surface—ride height and kerb usage evolve through weekend.',
  ],
  'mexico_city': [
    'Track: thin air, long straights—low drag; watch brake temps into the stadium section.',
    'Strategy: altitude hurts cooling—lift-and-coast can appear; strategy stacks around SC.',
    'Weather: afternoon storms—track can cool quickly; inter calls on the perimeter.',
    'Racecraft: Turn 1 is wide—three-wide risk; defend inside early for the esses.',
    'Session plan: FP2 at altitude mirrors race—fuel-correct long runs for deg truth.',
  ],
  'sao_paulo': [
    'Track: Senna S and middle sector—Interlagos needs mechanical grip and patience.',
    'Strategy: sprint weekend possible—tyre steps and SC history keep strategies open.',
    'Weather: sudden rain in the hills—rivers at Senna S when it pours.',
    'Racecraft: Turn 1 and Pinheirinha—cutback moves work if you leave a car width.',
    'Session plan: altitude and bumps—re-check quali trim after rubber builds in FP2.',
  ],
  'las_vegas': [
    'Track: long straights, low grip off-line—street walls; traction out of slow corners wins.',
    'Strategy: cold night temps—tyre warm-up laps matter; graining on long runs possible.',
    'Weather: desert cold at night—rear grip can surprise on the long strip.',
    'Racecraft: few clean passes—set up on the long braking zones; avoid wall contact.',
    'Session plan: late sessions mirror race—prioritise long runs when track temp matches.',
  ],
  'qatar': [
    'Track: high-speed corners stress fronts—smooth inputs keep the tyres under you.',
    'Strategy: abrasive surface—two-stop common; pit lane loss vs deg is the trade.',
    'Weather: desert wind and sand—front grip varies; track limits are strict.',
    'Racecraft: long straights into heavy braking—tow and DRS trains decide moves.',
    'Session plan: night conditions in FP2—baseline long runs for Sunday temps.',
  ],
  'abu_dhabi': [
    'Track: traction out of the hotel section sets the marina straights—rear stability first.',
    'Strategy: one-stop often wins—track position and undercut threat around pit loss matter.',
    'Weather: evening humidity—dew can appear late race; grip can come up suddenly.',
    'Racecraft: Turns 5–6 and the hotel chicane—defend inside, avoid wide exits onto paint.',
    'Session plan: twilight evolution—qualifying after sunset can feel like a different track.',
  ],
};

const Map<String, List<String>> _coachNl = {
  'fallback': [
    'Circuit: ritme in sector 2 en achterbanden sparen—schone exits worden hier beloond.',
    'Strategie: wissel tussen één en twee stops na FP2-degradatie; undercut is echt.',
    'Weer: wind op de langste rechters—trim de aero bij dwarswind.',
    'Racecraft: pak de binnenkant in de eerste zware remzone; de volgende rechter straft een slechte exit.',
    'Sessie: eerst FP2-lange runs, dan kwalificatiesim als er rubber ligt.',
  ],
  'australian': [
    'Circuit: bochten 3–4 belonen een nette exit—Albert Park straft gierig gas langs het meer.',
    'Strategie: twee stops Medium/Hard is normaal; safety cars kunnen alles omgooien—blijf flexibel.',
    'Weer: wisselende koele lucht van de baai—grip kan per sessie verschuiven.',
    'Racecraft: DRS langs Lakeside Drive—bereid de inhaal voor op zware rem naar het stadion.',
    'Sessie: FP2 is je bandenreferentie; korte rondes en traffic maken schone long runs goud.',
  ],
  'chinese': [
    'Circuit: de “Slak” vraagt geduld; de lange achterrechte beloont tractie.',
    'Strategie: sprintweekend—bandenbudget is krap; spaar softs voor SQ en race.',
    'Weer: lente in Shanghai kan regen geven—let op spray op lange rechte inritten.',
    'Racecraft: bocht 1 is breed—verdedig binnen maar offer de run naar de lange rechter niet op.',
    'Sessie: sprintkwali = minder rondes—nail de evolutie tussen SQ en race.',
  ],
  'japanese': [
    'Circuit: 130R en de Esses willen flow—Suzuka is ritme, niet stampen.',
    'Strategie: één stop Medium/Hard wint vaak; pitverlies doet pijn—positie telt.',
    'Weer: herfst in Honshu kan nat—inter-timing rond Degner is cruciaal.',
    'Racecraft: Casio Triangle is een loterij—rem laat maar ruimte voor cutback.',
    'Sessie: bandenwarmloop bij koude ochtend—long runs in representatieve warmte.',
  ],
  'bahrain': [
    'Circuit: tractie uit de laatste bocht bepaalt de hoofdrechte—achterstabiliteit eerst.',
    'Strategie: nachtrace in de woestijn—twee stops typisch; undercut als het veld stapel.',
    'Weer: koele avond maar zand op het asfalt—voorste grip wisselt per ronde.',
    'Racecraft: bochten 1 en 4 zijn inhaalpunten—verdedig vroeg, niet breed op tractieverf.',
    'Sessie: FP2 volgt racecondities—long runs bij kunstlicht is je baseline.',
  ],
  'saudi_arabian': [
    'Circuit: blinde inritten en beton—commitment in snelle knikken, overleven eerst.',
    'Strategie: hoge degradatie—twee stops gebruikelijk; SC kan het veld dicht trekken.',
    'Weer: kustvocht ’s nachts—dauw en veranderende achtergrip.',
    'Racecraft: weinig schone inhaalpunten—zet aan bij chicanes, niet tegen de muur.',
    'Sessie: korte training—elke ronde telt; vermijd traffic in kwalificatiesims.',
  ],
  'miami': [
    'Circuit: lange bochten, weinig grip off-line—geduld; jachthaven straft fouten.',
    'Strategie: hitte en tractie—twee stops opent bij SC.',
    'Weer: Florida-onweer—radar telt; inter-timing op lange rechters.',
    'Racecraft: smalle bochten na lange rechters—rem in rechte lijn, geen lock-up off-line.',
    'Sessie: rubber komt snel—late vrijdag-kwalificatiesim weegt zwaarder dan vroege ronden.',
  ],
  'canadian': [
    'Circuit: Wall of Champions—laatste chicane vraagt precisie; niet te wild over kerbs.',
    'Strategie: stop-go—undercut met lang pitverlies is sterk als traffic het toelaat.',
    'Weer: wisselende zomers in Montreal—regen kan snel komen; grip op de hairpin verandert.',
    'Racecraft: Hairpin en Senna S—rem laat maar bescherm binnen voor de exit.',
    'Sessie: kerb-evolutie verschuift balans—herhaal kwalitrim na rubber.',
  ],
  'monaco': [
    'Circuit: geen ruimte voor fout—elke bocht is kwalificatie; ritme wint van heldendom.',
    'Strategie: positie > strategie—overcut wint zelden van volgorde op de baan.',
    'Weer: zelden nat in de stad—bij regen wordt de haven ijs op slicks.',
    'Racecraft: tunneluit en Nouvelle zijn hinderlagen—verdedig vroeg in de spiegels.',
    'Sessie: donderdag/vrijdag traffic-puzzel—vind schone kwalironden vóór zaterdag.',
  ],
  'barcelona': [
    'Circuit: sector 3-tractie naar de rechte bepaalt slipstream—achterstabiliteit wint.',
    'Strategie: slijtage linksvoor—één vs twee stops met baantemp.',
    'Weer: Catalaanse wind over het grid—balans verschuift per bocht.',
    'Racecraft: bocht 1 en laatste complex—offer de run naar Campsa niet op.',
    'Sessie: FP2-hitte representatief—ochtendzand kan long runs misleiden.',
  ],
  'austrian': [
    'Circuit: korte ronde, groot slipstream—tow-spelletjes en DRS-treinen.',
    'Strategie: soft-offset mogelijk—pitlane kort, undercuts doen pijn.',
    'Weer: Alpen-buien—sector 1 nat, sector 3 droog kan.',
    'Racecraft: bochten 3–4 en laatste bocht—verdedig vóór de klim.',
    'Sessie: traffic op 4,3 km—boek schone kwalironden vroeg in het venster.',
  ],
  'british': [
    'Circuit: hoge snelheid—Copse, Maggots, Becketts belonen commitment en stabiele achterkant.',
    'Strategie: blister bij hitte—één vs twee stops met asfalttemp.',
    'Weer: Silverstone-wind en buien—inter vs full wets bepalen weekend.',
    'Racecraft: Hangar Straight DRS—bereid de inhaal vóór Stowe.',
    'Sessie: vrijdagwind vs zaterdagrust—check aero vóór kwalificatie.',
  ],
  'belgian': [
    'Circuit: Eau Rouge–Raidillon respect—licht liften als de achterkant licht voelt.',
    'Strategie: lange ronde, groot pitverlies—undercut/overcut; SC-kans hoog.',
    'Weer: Ardennen-microklimaat—nat aan één kant, droog aan de andere.',
    'Racecraft: Les Combes en Bus Stop—rem recht, vermijd kerb-hop.',
    'Sessie: FP2 in mix kan liegen—prioriteit droge baseline als race droog is.',
  ],
  'hungarian': [
    'Circuit: kronkelig Hungaroring—sector 2-ritme; voorbanden sparen in lange bochten.',
    'Strategie: moeilijk inhalen—kwalificatie telt; één vs twee stops met traffic.',
    'Weer: heet Boedapest—achterband te warm in traffic; thermische degradatie.',
    'Racecraft: bocht 1 en chicane—binnen verdedigen, niet breed.',
    'Sessie: lage snelheid verschuift met brandstof—kwalifuur in laatste training.',
  ],
  'dutch': [
    'Circuit: banking en wind—smal Zandvoort; één fout stapelt een trein.',
    'Strategie: one-stop lastig in traffic—twee stops als degradatie opent.',
    'Weer: Noordzee-wind—dwarswind in banking verandert balans per ronde.',
    'Racecraft: Tarzan en Hans Ernst—laat remmen met strakke rotatie.',
    'Sessie: oranje rook in kwali—kies vroeg een schone out-lap.',
  ],
  'italian': [
    'Circuit: lage drag, hoge snelheid—Monza is slipstream-schaak; tow in kwali beslist rijen.',
    'Strategie: één vs twee stops met SC—pitlane kort, veld blijft dicht.',
    'Weer: late zomerstorm—plots regen op rechters terwijl Lesmo droog blijft.',
    'Racecraft: Rettifilo en della Roggia—rem laat maar raak de apex.',
    'Sessie: track limits Ascari/Parabolica—trim wing na FP1-baseline.',
  ],
  'spanish_madrid': [
    'Circuit: nieuw hybride layout—leer referenties; muren en grip nog onbekend.',
    'Strategie: groen asfalt evolueert snel—twee stops tot degradatie stabiel is.',
    'Weer: Madrid-hitte en stof—grip springt als de lijn rubber krijgt.',
    'Racecraft: onbekende inhaalpunten—binnen beschermen op lange rechters.',
    'Sessie: elke sessie is data—korte vs lange runs voor bandenkruising.',
  ],
  'azerbaijan': [
    'Circuit: lange rechters naar 90°—Baku straft lockups; kasteel is muur aan muur.',
    'Strategie: SC-kans—splitstrategieën; pit-in snelheid vangt fouten.',
    'Weer: Kaspische wind op de hoofdrechte—remzones lengen met tegenwind.',
    'Racecraft: bocht 1 en kasteel—vroeg duiken of niet; geen halve moves.',
    'Sessie: FP1-stof vs avondrubber—kwalificeer op laatste representatieve baan.',
  ],
  'singapore': [
    'Circuit: hobbelig stratencircuit, 23 bochten—mentaal zwaar; voorbanden lijden.',
    'Strategie: lange race, hoge deg—twee stops basis; SC bundelt het veld.',
    'Weer: tropische buien—inter-timing op lange rechters beslist podia.',
    'Racecraft: weinig schone plekken—zet aan bij Raffles; geen kerb-hop onder rem.',
    'Sessie: nachtwarmte vs kwali-avond—evolutie FP2→Q3 is groot.',
  ],
  'united_states': [
    'Circuit: esses sector 1 willen flow; achterstabiliteit naar de lange achterrechte.',
    'Strategie: degradatie op tractie—één vs twee stops met baantemp.',
    'Weer: Texas-wind en hitte—balans wisselt; dwarswind in de esses.',
    'Racecraft: bocht 1 en hairpin—laat remmen met gecontroleerde rotatie.',
    'Sessie: hobbelig Austin—ride height en kerbs evolueren door het weekend.',
  ],
  'mexico_city': [
    'Circuit: ijle lucht, lange rechters—lage drag; remtemp naar het stadion.',
    'Strategie: hoogte kost koeling—lift-and-coast mogelijk; SC stapelt strategie.',
    'Weer: middagbuien—baan koelt snel; inter aan de rand.',
    'Racecraft: bocht 1 breed—driewijdig risico; verdedig vroeg voor de esses.',
    'Sessie: FP2 op hoogte als race—brandstof-gecorrigeerde long runs.',
  ],
  'sao_paulo': [
    'Circuit: Senna S en middenstuk—Interlagos wil mechanische grip en geduld.',
    'Strategie: sprintweekend mogelijk—bandenstappen en SC houden opties open.',
    'Weer: plots regen in de heuvels—rivieren bij Senna S bij stortbui.',
    'Racecraft: bocht 1 en Pinheirinha—cutback werkt met een auto breedte.',
    'Sessie: hoogte en hobbel—herhaal kwalitrim na rubber in FP2.',
  ],
  'las_vegas': [
    'Circuit: lange rechters, weinig grip off-line—straten; tractie uit trage bochten wint.',
    'Strategie: koude nacht—bandenwarm-up telt; graining op long runs mogelijk.',
    'Weer: woestijnkou ’s nachts—achtergrip kan verrassen op de Strip.',
    'Racecraft: weinig schone passes—zet aan op lange remzones; geen muur.',
    'Sessie: late sessies als race—long runs bij vergelijkbare baantemp.',
  ],
  'qatar': [
    'Circuit: hoge snelheid belast voorbanden—vloeiende stuurbewegingen.',
    'Strategie: schurend asfalt—twee stops gebruikelijk; pitverlies vs degradatie.',
    'Weer: woestijnwind en zand—voorste grip wisselt; strikte track limits.',
    'Racecraft: lange rechters naar zware rem—tow en DRS-treinen bepalen moves.',
    'Sessie: nacht-FP2—baseline long runs voor zondagtemp.',
  ],
  'abu_dhabi': [
    'Circuit: tractie uit hotel-sectie naar marina-rechters—achterstabiliteit eerst.',
    'Strategie: één stop wint vaak—positie en undercut rond pitverlies.',
    'Weer: avondvocht—dauw laat in de race; grip kan plots komen.',
    'Racecraft: bochten 5–6 en hotel-chicane—binnen verdedigen, niet breed op verf.',
    'Sessie: schemering evolueert—kwali na zonsondergang voelt anders.',
  ],
};

const Map<String, List<String>> _coachDe = {
  'fallback': [
    'Strecke: Rhythmus in Sektor 2 und Hinterreifen schonen—saubere Exits zählen.',
    'Strategie: zwischen einem und zwei Stopps nach FP2 flexen; Undercut ist real.',
    'Wetter: Böen auf den langen Geraden—Aero bei Seitenwind nachjustieren.',
    'Racecraft: Innenlinie in die erste harte Bremszone; die nächste Gerade bestraft schlechte Exits.',
    'Session: zuerst FP2-Langläufe, dann Qualifying-Sims mit Rubber auf der Strecke.',
  ],
  'australian': [
    'Strecke: Kurven 3–4 belohnen sauberen Exit—Albert Park bestraft gieriges Gas am See.',
    'Strategie: Zwei-Stopp Medium/Hard üblich; Safety Cars können alles drehen—flexibel bleiben.',
    'Wetter: wechselhafte kühle Luft von der Bucht—Grip kann pro Session schwanken.',
    'Racecraft: DRS entlang Lakeside Drive—Angriff vor der schweren Bremsung ins Stadion vorbereiten.',
    'Session: FP2 als Reifenreferenz; Kurze Runden und Traffic machen saubere Longruns wertvoll.',
  ],
  'chinese': [
    'Strecke: „Schnecken“-Komplex braucht Geduld; lange Gerade belohnt Traktion.',
    'Strategie: Sprint-Wochenende—Reifenbudget knapp; Softs für SQ und Rennen schonen.',
    'Wetter: Frühling in Shanghai kann Regen bringen—Aufspritz auf langen Geraden.',
    'Racecraft: Kurve 1 ist breit—innen verteidigen, aber Lauf zur langen Geraden nicht opfern.',
    'Session: Sprint-Quali bedeutet weniger Runden—Evolution zwischen SQ und Rennen.',
  ],
  'japanese': [
    'Strecke: 130R und Esses wollen Fluss—Suzuka ist Rhythmus, nicht Stampfen.',
    'Strategie: Ein Stopp Medium/Hard oft schnell; Boxenzeit weh—Position zählt.',
    'Wetter: Herbst in Honshu kann nass sein—Intermediate-Timing um Degner entscheidend.',
    'Racecraft: Casio-Dreieck ist Lotterie—spät bremsen, Platz für Cutback lassen.',
    'Session: Reifenwarmfahren bei kühlem Morgen—Longruns in repräsentativer Wärme.',
  ],
  'bahrain': [
    'Strecke: Traktion aus letzter Kurve setzt Hauptgerade—Heckstabilität zuerst.',
    'Strategie: Nachtrennen in der Wüste—zwei Stopps typisch; Undercut bei Stau.',
    'Wetter: kühler Abend aber Sand—Vordergriff schwankt rundenweise.',
    'Racecraft: Kurven 1 und 4 sind Angriffspunkte—früh verteidigen, nicht breit auf Grip.',
    'Session: FP2 spiegelt Rennbedingungen—Longruns unter Licht die Basis.',
  ],
  'saudi_arabian': [
    'Strecke: blinde Einfahrten und Beton—Commitment in schnellen Knicken, Überleben zuerst.',
    'Strategie: hohe Degradation—zwei Stopps üblich; SC kann das Feld schließen.',
    'Wetter: Küstenfeuchtigkeit nachts—Tau und wechselnder Heckgriff.',
    'Racecraft: wenige saubere Überholpunkte—Chicanes nutzen, nicht die Wand suchen.',
    'Session: kurzes Training—jede Runde zählt; Traffic in Quali-Sims vermeiden.',
  ],
  'miami': [
    'Strecke: lange Kurven, wenig Grip neben der Linie—Disziplin; Marina bestraft Fehler.',
    'Strategie: Hitze und Traktionszonen—zwei Stopps wenn SC aufgeht.',
    'Wetter: Florida-Gewitter—Radar zählt; Intermediate auf langen Geraden.',
    'Racecraft: enge Kurven nach langen Geraden—gerade bremsen, kein Lock-up neben der Linie.',
    'Session: Asphalt rubbert schnell—späte Freitags-Quali-Sims wichtiger als frühe Runden.',
  ],
  'canadian': [
    'Strecke: Wall of Champions—letzte Chicane will Präzision; Kerbs nicht überfordern.',
    'Strategie: Stop-and-Go—Undercut mit langem Boxenverlust stark wenn Traffic passt.',
    'Wetter: wechselhafte Montreal-Sommer—Regen schnell da; Haarnadel-Griff ändert sich.',
    'Racecraft: Haarnadel und Senna S—spät bremsen, innen für Exit schützen.',
    'Session: Kerb-Evolution verschiebt Balance—Quali-Setup nach Rubber neu fahren.',
  ],
  'monaco': [
    'Strecke: kein Raum für Fehler—jede Kurve wie Qualifying; Rhythmus schlägt Heldentum.',
    'Strategie: Position > Strategie—Overcut schlägt selten die Reihenfolge auf der Strecke.',
    'Wetter: selten nass in der Stadt—bei Regen wird der Hafenbereich zur Eisbahn.',
    'Racecraft: Tunnel-Ausgang und Nouvelle—früh in den Spiegeln verteidigen.',
    'Session: Do/Fr Traffic-Puzzle—saubere Quali-Runden vor Samstag finden.',
  ],
  'barcelona': [
    'Strecke: Sektor-3-Traktion zur Geraden entscheidet Slipstream—Heckstabilität gewinnt.',
    'Strategie: Verschleiß vorne links—ein vs zwei Stopps mit Streckentemperatur.',
    'Wetter: katalanischer Wind über dem Grid—Balance wechselt pro Kurve.',
    'Racecraft: Kurve 1 und letzter Komplex—Lauf Richtung Campsa nicht opfern.',
    'Session: FP2-Hitze repräsentativ—Morgensand kann Longruns täuschen.',
  ],
  'austrian': [
    'Strecke: kurze Runde, großer Slipstream—Tow-Spiele und DRS-Züge.',
    'Strategie: Soft-Offset möglich—Boxengasse kurz, Undercuts tun weh.',
    'Wetter: Alpen-Schauer—Sektor 1 nass, Sektor 3 trocken möglich.',
    'Racecraft: Kurven 3–4 und letzte Kurve—vor dem Anstieg verteidigen.',
    'Session: Traffic auf 4,3 km—früh im Fenster saubere Quali-Runden buchen.',
  ],
  'british': [
    'Strecke: hohe Geschwindigkeit—Copse, Maggots, Becketts belohnen Commitment und stabiles Heck.',
    'Strategie: Blister bei Hitze—ein vs zwei Stopps mit Asphalttemperatur.',
    'Wetter: Silverstone-Wind und Schauer—Intermediate vs Full Wet entscheidet.',
    'Racecraft: Hangar Straight DRS—Angriff vor Stowe vorbereiten.',
    'Session: Freitagswind vs Samstag—Aero vor Quali neu checken.',
  ],
  'belgian': [
    'Strecke: Eau Rouge–Raidillon respektieren—leicht anheben wenn das Heck leicht wird.',
    'Strategie: lange Runde, großer Boxenverlust—Undercut/Overcut; SC-Wahrscheinlichkeit hoch.',
    'Wetter: Ardennen-Mikroklima—eine Seite nass, andere trocken.',
    'Racecraft: Les Combes und Bus Stop—gerade bremsen, Kerb-Hop vermeiden.',
    'Session: FP2 bei Mix kann trügen—trockene Basis wenn Rennen trocken.',
  ],
  'hungarian': [
    'Strecke: kringeliger Hungaroring—Sektor-2-Rhythmus; Vorderreifen in langen Kurven schonen.',
    'Strategie: schwer zu überholen—Quali zählt; ein vs zwei Stopps mit Traffic.',
    'Wetter: heißes Budapest—Heck in Traffic heiß; thermische Degradation.',
    'Racecraft: Kurve 1 und Chicane—innen verteidigen, nicht breit.',
    'Session: niedrige Geschwindigkeit mit Sprit—Quali-Fuel im letzten Training.',
  ],
  'dutch': [
    'Strecke: Banking und Wind—enges Zandvoort; ein Fehler stapelt eine Kette.',
    'Strategie: Ein-Stopp im Traffic schwer—zwei Stopps wenn Deg aufgeht.',
    'Wetter: Nordsee-Böen—Seitenwind im Banking ändert Balance jede Runde.',
    'Racecraft: Tarzan und Hans Ernst—spät bremsen mit straffer Rotation.',
    'Session: orangefarbener Rauch in der Quali—früh freie Out-Lap sichern.',
  ],
  'italian': [
    'Strecke: niedriger Drag, hohe Geschwindigkeit—Monza ist Slipstream-Schach; Tow in der Quali.',
    'Strategie: ein vs zwei Stopps mit SC—Box kurz, Feld bleibt dicht.',
    'Wetter: Spätsommer-Stürme—Regen auf Geraden, Lesmo trocken.',
    'Racecraft: Rettifilo und della Roggia—spät bremsen, Apex treffen.',
    'Session: Track Limits Ascari/Parabolica—Flügel nach FP1-Baseline trimmen.',
  ],
  'spanish_madrid': [
    'Strecke: neues Hybrid-Layout—Referenzen lernen; Wände und Grip zunächst unbekannt.',
    'Strategie: grüne Strecke entwickelt sich schnell—zwei Stopps bis Deg stabil ist.',
    'Wetter: Madrid-Hitze und Staub—Grip springt wenn die Linie rubbert.',
    'Racecraft: unbekannte Überholzonen—innen auf langen Geraden schützen.',
    'Session: jede Session ist Datenkurz- vs Langläufe für Reifen-Crossover.',
  ],
  'azerbaijan': [
    'Strecke: lange Geraden in 90°—Baku bestraft Blockaden; Burg eng zwischen Mauern.',
    'Strategie: SC-Wahrscheinlichkeit—Split-Strategien; Boxeneinfahrt-Geschwindigkeit fällt auf.',
    'Wetter: Kaspisches Wind auf der Hauptgerade—Bremszonen verlängern sich mit Gegenwind.',
    'Racecraft: Kurve 1 und Burg-Chicane—früh oder gar nicht; keine halben Moves.',
    'Session: FP1-Staub vs Abend-Rubber—Quali auf letztem repräsentativen Asphalt.',
  ],
  'singapore': [
    'Strecke: holprige Straße, 23 Kurven—hohe mentale Last; Vorderreifen leiden.',
    'Strategie: langes Rennen, hohe Deg—zwei Stopps Basis; SC bündelt das Feld.',
    'Wetter: tropische Stürme—Intermediate auf langen Geraden entscheidet Podien.',
    'Racecraft: wenige saubere Stellen—Raffles vorbereiten; kein Kerb-Hopping unter Bremse.',
    'Session: Nachtwärme vs Quali-Abend—Evolution FP2→Q3 ist groß.',
  ],
  'united_states': [
    'Strecke: Esses Sektor 1 wollen Fluss; Heckstabilität zur langen Geraden.',
    'Strategie: Deg auf Traktionszonen—ein vs zwei Stopps mit Asphalttemp.',
    'Wetter: Texas-Böen und Hitze—Balance wechselt; Seitenwind in den Esses.',
    'Racecraft: Kurve 1 und Hairpin—spät bremsen mit kontrollierter Rotation.',
    'Session: holprige Austin-Oberfläche—Ride-Höhe und Kerbs entwickeln sich.',
  ],
  'mexico_city': [
    'Strecke: dünne Luft, lange Geraden—niedriger Drag; Bremsen-Temp ins Stadion.',
    'Strategie: Höhe kostet Kühlung—Lift-and-Coast möglich; SC stapelt Strategie.',
    'Wetter: Nachmittagsgewitter—Strecke kühlt schnell; Inter am Rand.',
    'Racecraft: Kurve 1 breit—drei breit Risk; früh für Esses verteidigen.',
    'Session: FP2 in Höhe wie Rennen—kraftstoffkorrigierte Longruns.',
  ],
  'sao_paulo': [
    'Strecke: Senna S und Mittelsektor—Interlagos will mechanischen Grip und Geduld.',
    'Strategie: Sprint-Wochenende möglich—Reifenstufen und SC halten Optionen offen.',
    'Wetter: plötzlicher Regen in den Hügeln—Fluten in Senna S bei Starkregen.',
    'Racecraft: Kurve 1 und Pinheirinha—Cutback mit einer Auto Breite.',
    'Session: Höhe und Buckel—Quali-Setup nach FP2-Rubber neu fahren.',
  ],
  'las_vegas': [
    'Strecke: lange Geraden, wenig Grip neben der Linie—Wände; Traktion aus langsamen Kurven.',
    'Strategie: kalte Nacht—Reifenwarmfahren zählt; Graining auf Longruns möglich.',
    'Wetter: Wüstenkälte nachts—Heckgriff auf dem Strip kann überraschen.',
    'Racecraft: wenige saubere Überholungen—lange Bremszonen nutzen; keine Wand.',
    'Session: späte Sessions wie Rennen—Longruns bei ähnlicher Streckentemp.',
  ],
  'qatar': [
    'Strecke: hohe Geschwindigkeit belastet Vorderreifen—sanfte Inputs.',
    'Strategie: abrasiver Asphalt—zwei Stopps üblich; Boxenzeit vs Deg.',
    'Wetter: Wüstenwind und Sand—Vordergriff schwankt; strikte Track Limits.',
    'Racecraft: lange Geraden in harte Bremsen—Tow und DRS-Züge entscheiden.',
    'Session: Nacht-FP2—Baseline-Longruns für Sonntagstemperaturen.',
  ],
  'abu_dhabi': [
    'Strecke: Traktion aus Hotel-Sektion zu Marina-Geraden—Heck zuerst.',
    'Strategie: ein Stopp gewinnt oft—Position und Undercut um Boxenzeit.',
    'Wetter: abendliche Feuchtigkeit—Tau spät im Rennen; Grip kann kommen.',
    'Racecraft: Kurven 5–6 und Hotel-Chicane—innen verteidigen, nicht breit auf Farbe.',
    'Session: Dämmerung entwickelt sich—Quali nach Sonnenuntergang anderes Gefühl.',
  ],
};

const Map<String, List<String>> _coachFr = {
  'fallback': [
    'Piste : rythme en secteur 2 et ménager les arrière—les sorties propres paient.',
    'Stratégie : flex entre un et deux arrêts après les longs runs FP2 ; l’undercut compte.',
    'Météo : rafales sur les longues lignes droites—rééquilibrer l’aéro si vent de travers.',
    'Racecraft : prendre l’intérieur dans le premier gros freinage ; la prochaine ligne droite punira une mauvaise sortie.',
    'Plan de session : d’abord longs runs FP2, puis sims de qualifs quand la piste est encrassée.',
  ],
  'australian': [
    'Piste : virages 3–4 récompensent une sortie propre—Albert Park punit l’accélérateur trop tôt au bord du lac.',
    'Stratégie : deux arrêts Medium/Hard fréquents ; safety cars peuvent tout mélanger—restez souple.',
    'Météo : air frais changeant depuis la baie—l’adhérence peut varier entre les sessions.',
    'Racecraft : DRS le long de Lakeside Drive—préparer le dépassement avant le freinage vers le stade.',
    'Session : FP2 comme référence pneus ; tours courts et trafic rendent les longs runs précieux.',
  ],
  'chinese': [
    'Piste : le complexe « escargot » demande de la patience ; la longue ligne droite arrière récompense la traction.',
    'Stratégie : week-end sprint—budget pneus serré ; ménager les softs pour SQ et course.',
    'Météo : printemps à Shanghai—pluie possible ; attention à l’aquaplaning en entrée de ligne droite.',
    'Racecraft : le virage 1 est large—défendre l’intérieur sans sacrifier la ligne vers la longue droite.',
    'Session : qualif sprint = moins de tours—maîtriser l’évolution entre SQ et course.',
  ],
  'japanese': [
    'Piste : 130R et les S exigent du rythme—Suzuka est une piste de flow.',
    'Stratégie : un arrêt Medium/Souvent le plus rapide ; la perte au stand fait mal—la position compte.',
    'Météo : automne à Honshu—pluie possible ; choix inters autour de Degner.',
    'Racecraft : le triangle Casio est une loterie—freiner tard mais laisser une porte au cutback.',
    'Session : mise en température le matin—longs runs dans une chaleur représentative.',
  ],
  'bahrain': [
    'Piste : la traction sortie du dernier virage prépare la ligne droite—stabilité arrière d’abord.',
    'Stratégie : course de nuit au désert—deux arrêts typiques ; undercut si le peloton se tasse.',
    'Météo : soir frais mais sable—adhérence avant variable tour après tour.',
    'Racecraft : virages 1 et 4 pour attaquer—défendre tôt, ne pas partir large sur la peinture.',
    'Session : FP2 reflète la course—longs runs sous les projecteurs comme base.',
  ],
  'saudi_arabian': [
    'Piste : entrées aveugles et béton—engagement dans les enchaînements rapides, survie d’abord.',
    'Stratégie : forte dégradation—deux arrêts fréquents ; safety cars resserrent le peloton.',
    'Météo : humidité côtière la nuit—rosée et grip arrière changeant.',
    'Racecraft : peu de zones propres—préparer aux chicanes, éviter les murs.',
    'Session : essais courts—chaque tour compte ; éviter le trafic en sims de qualifs.',
  ],
  'miami': [
    'Piste : longs virages, peu d’adhérence hors ligne—discipline ; la marina punit les erreurs.',
    'Stratégie : chaleur et zones de traction—fenêtre à deux arrêts si safety car.',
    'Météo : orages en Floride—radar utile ; inters sur les longues lignes droites.',
    'Racecraft : virages serrés après longues lignes droites—freiner en ligne droite, pas de blocage hors ligne.',
    'Session : la piste encrasse vite—sim de qualif tardive vendredi plus parlante que tôt.',
  ],
  'canadian': [
    'Piste : Wall of Champions—dernière chicane exige de la précision ; ne pas abuser des vibreurs.',
    'Stratégie : circuit stop-and-go—undercut puissant si la perte au stand et le trafic le permettent.',
    'Météo : été variable à Montréal—pluie rapide ; grip du épingle changeant.',
    'Racecraft : épingle et S de Senna—freiner tard mais protéger l’intérieur pour la sortie.',
    'Session : évolution des vibreurs change l’équilibre—reprendre le trim de qualif après le rubber.',
  ],
  'monaco': [
    'Piste : aucune marge—chaque virage est un tour qualif ; le rythme bat les héroïsmes.',
    'Stratégie : position > stratégie—l’overcut ne bat pas souvent l’ordre sur piste.',
    'Météo : rarement humide en ville—si pluie, le port devient glacé en slicks.',
    'Racecraft : sortie du tunnel et Nouvelle chicane—défendre tôt dans les rétros.',
    'Session : puzzle de trafic jeu/vendredi—trouver des tours propres avant samedi.',
  ],
  'barcelona': [
    'Piste : traction secteur 3 vers la ligne droite—stabilité arrière pour le slipstream.',
    'Stratégie : usure avant gauche—un ou deux arrêts selon température de piste.',
    'Météo : vent catalan sur la grille—balance différente à chaque virage.',
    'Racecraft : virage 1 et dernier complexe—ne pas sacrifier la ligne vers Campsa.',
    'Session : chaleur FP2 représentative—sable matinal peut tromper les longs runs.',
  ],
  'austrian': [
    'Piste : tour court, gros slipstream—jeux de remorque et trains DRS.',
    'Stratégie : offset soft possible—voie des stands courte, undercuts font mal.',
    'Météo : averses alpines—secteur 1 mouillé, secteur 3 sec possible.',
    'Racecraft : virages 3–4 et dernier virage—défendre avant la montée.',
    'Session : trafic sur 4,3 km—réserver des tours propres tôt dans la fenêtre.',
  ],
  'british': [
    'Piste : haute vitesse—Copse, Maggots, Becketts récompensent l’engagement et l’arrière stable.',
    'Stratégie : ébullition en chaleur—un ou deux arrêts selon température d’asphalte.',
    'Météo : vent et averses à Silverstone—choix inter vs full wet.',
    'Racecraft : DRS sur Hangar Straight—préparer le dépassement avant Stowe.',
    'Session : vent vendredi vs calme samedi—revérifier l’aéro avant les qualifs.',
  ],
  'belgian': [
    'Piste : Eau Rouge–Raidillon—respect ; lever légèrement si l’arrière est légère.',
    'Stratégie : long tour, grosse perte au stand—undercut/overcut ; forte proba de SC.',
    'Météo : microclimat des Ardennes—une extrémité mouillée, l’autre sèche.',
    'Racecraft : Les Combes et Bus Stop—freiner droit, éviter le saut sur les vibreurs.',
    'Session : FP2 mixte peut mentir—prioriser la base sèche si la course est sèche.',
  ],
  'hungarian': [
    'Piste : Hungaroring sinueux—rythme secteur 2 ; ménager les avant sur les longs virages.',
    'Stratégie : difficile de dépasser—qualifs cruciales ; un ou deux arrêts selon trafic.',
    'Météo : chaleur de Budapest—arrière chaud dans le trafic ; dégradation thermique.',
    'Racecraft : virage 1 et chicane—défendre l’intérieur, ne pas partir large.',
    'Session : basse vitesse avec carburant—niveau qualif dans la dernière séance.',
  ],
  'dutch': [
    'Piste : banking et vent—Zandvoort étroit ; une erreur empile un train.',
    'Stratégie : un arrêt difficile dans le trafic—deux arrêts si la deg s’ouvre.',
    'Météo : rafales du Nord—vent de travers dans le banking change la balance chaque tour.',
    'Racecraft : Tarzan et Hans Ernst—freiner tard avec une rotation serrée.',
    'Session : fumée orange en qualif—choisir tôt un tour de sortie propre.',
  ],
  'italian': [
    'Piste : faible appui, haute vitesse—Monza est un jeu de slipstream ; remorque en qualif.',
    'Stratégie : un ou deux arrêts avec SC—stands courts, peloton dense.',
    'Météo : orages de fin d’été—pluie sur les lignes droites, Lesmo au sec.',
    'Racecraft : Rettifilo et della Roggia—freiner tard mais prendre l’apex.',
    'Session : limites de piste Ascari/Parabolica—réduire l’aile après FP1.',
  ],
  'spanish_madrid': [
    'Piste : nouveau tracé hybride—apprendre les repères ; murs et grip encore inconnus.',
    'Stratégie : piste verte qui évolue vite—deux arrêts jusqu’à stabilisation de la dégradation.',
    'Météo : chaleur et poussière madrilène—le grip bondit quand la ligne encrasse.',
    'Racecraft : zones de dépassement inconnues—protéger l’intérieur sur les longues lignes.',
    'Session : chaque séance est de la donnée—courts vs longs runs pour le crossover pneus.',
  ],
  'azerbaijan': [
    'Piste : longues lignes droites en 90°—Baku punit le blocage ; château entre murs.',
    'Stratégie : forte proba de SC—stratégies scindées ; vitesse d’entrée aux stands piège.',
    'Météo : vent caspien sur la ligne droite—zones de freinage allongées avec vent de face.',
    'Racecraft : virage 1 et château—plonger tôt ou pas ; pas de demi-mesures.',
    'Session : poussière FP1 vs gomme le soir—qualif sur le dernier asphalte représentatif.',
  ],
  'singapore': [
    'Piste : rue bosselée, 23 virages—charge mentale élevée ; avant souffrent.',
    'Stratégie : longue course, forte dég—deux arrêts de base ; SC resserre souvent.',
    'Météo : orages tropicaux—choix d’inters sur les longues lignes droites.',
    'Racecraft : peu de zones propres—préparer Raffles ; pas de saut sur vibreurs au frein.',
    'Session : chaleur nocturne vs soir de qualif—grosse évolution FP2→Q3.',
  ],
  'united_states': [
    'Piste : esses du secteur 1 en flow ; arrière stable vers la longue ligne droite.',
    'Stratégie : dég sur zones de traction—un ou deux arrêts selon température.',
    'Météo : rafales et chaleur au Texas—balance mobile ; vent dans les esses.',
    'Racecraft : virage 1 et épingle—freiner tard avec rotation contrôlée.',
    'Session : surface d’Austin bosselée—garde au sol et vibreurs évoluent.',
  ],
  'mexico_city': [
    'Piste : air rarefié, longues lignes—faible appui ; températures de frein vers le stade.',
    'Stratégie : altitude pénalise le refroidissement—lift-and-coast possible ; SC empile.',
    'Météo : orages d’après-midi—piste qui refroidit vite ; inter en périphérie.',
    'Racecraft : virage 1 large—risque à trois ; défendre tôt pour les esses.',
    'Session : FP2 en altitude comme la course—longs runs corrigés carburant.',
  ],
  'sao_paulo': [
    'Piste : Senna S et secteur médian—Interlagos veut grip mécanique et patience.',
    'Stratégie : week-end sprint possible—paliers pneus et SC gardent les options.',
    'Météo : pluie soudaine dans les collines—rivières au Senna S en averse.',
    'Racecraft : virage 1 et Pinheirinha—cutback si une largeur de voiture.',
    'Session : altitude et bosses—reprendre le setup qualif après le rubber FP2.',
  ],
  'las_vegas': [
    'Piste : longues lignes droites, peu d’adhérence hors ligne—murs ; traction des virages lents.',
    'Stratégie : nuit froide—mise en température des pneus ; graining possible en long run.',
    'Météo : froid désertique la nuit—surprise au niveau arrière sur le Strip.',
    'Racecraft : peu de dépassements propres—attaquer les longs freinages ; pas toucher les murs.',
    'Session : séances tardives comme la course—longs runs à température de piste proche.',
  ],
  'qatar': [
    'Piste : haute vitesse sollicite l’avant—inputs fluides.',
    'Stratégie : surface abrasive—deux arrêts fréquents ; perte stand vs dégradation.',
    'Météo : vent du désert et sable—adhérence avant variable ; limites strictes.',
    'Racecraft : longues lignes droites vers gros freinage—remorques et trains DRS.',
    'Session : FP2 nocturne—longs runs de référence pour dimanche.',
  ],
  'abu_dhabi': [
    'Piste : traction depuis la section hôtel vers les lignes marina—stabilité arrière d’abord.',
    'Stratégie : un arrêt gagne souvent—position et undercut autour de la perte au stand.',
    'Météo : humidité du soir—rosée en fin de course ; grip peut arriver vite.',
    'Racecraft : virages 5–6 et chicane hôtel—défendre l’intérieur, pas large sur la peinture.',
    'Session : crépuscule qui évolue—qualif après le coucher différente en feeling.',
  ],
};
