// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXdCsXLkUAgUPOCvleDX7RwHWkjVC0xLw',
    appId: '1:185602241236:web:3ca42ae70bb36e76a2c141',
    messagingSenderId: '185602241236',
    projectId: 'f1hub-5125e',
    authDomain: 'f1hub-5125e.firebaseapp.com',
    storageBucket: 'f1hub-5125e.firebasestorage.app',
    measurementId: 'G-FKYN6S16PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzCb1-MfHUGyC71fF_WRXP2wSj7r2oWco',
    appId: '1:185602241236:android:968fcd151dcd5839a2c141',
    messagingSenderId: '185602241236',
    projectId: 'f1hub-5125e',
    storageBucket: 'f1hub-5125e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuUnFMrsf5mC3rnCL-j3oep8HBVJNQZqQ',
    appId: '1:185602241236:ios:b9f8c46916323153a2c141',
    messagingSenderId: '185602241236',
    projectId: 'f1hub-5125e',
    storageBucket: 'f1hub-5125e.firebasestorage.app',
    iosClientId: '185602241236-9rio0t8bvelqeu23ch3u9l9oth409slc.apps.googleusercontent.com',
    iosBundleId: 'com.example.f1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuUnFMrsf5mC3rnCL-j3oep8HBVJNQZqQ',
    appId: '1:185602241236:ios:b9f8c46916323153a2c141',
    messagingSenderId: '185602241236',
    projectId: 'f1hub-5125e',
    storageBucket: 'f1hub-5125e.firebasestorage.app',
    iosClientId: '185602241236-9rio0t8bvelqeu23ch3u9l9oth409slc.apps.googleusercontent.com',
    iosBundleId: 'com.example.f1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXdCsXLkUAgUPOCvleDX7RwHWkjVC0xLw',
    appId: '1:185602241236:web:6402b1254774d80fa2c141',
    messagingSenderId: '185602241236',
    projectId: 'f1hub-5125e',
    authDomain: 'f1hub-5125e.firebaseapp.com',
    storageBucket: 'f1hub-5125e.firebasestorage.app',
    measurementId: 'G-K4MRYDR270',
  );

}