// Generate assets/data/circuits/specs_2026/<circuit_id>.json (24 × 2026 calendar).
// Run: dart run tool/gen_circuit_specs_2026.dart
import 'dart:convert';
import 'dart:io';

void main() {
  final dir = Directory('assets/data/circuits/specs_2026');
  if (!dir.existsSync()) {
    dir.createSync(recursive: true);
  }
  for (final spec in _specs) {
    final id = spec['circuit_id']! as String;
    File('${dir.path}/$id.json').writeAsStringSync(
      const JsonEncoder.withIndent('  ').convert(spec),
    );
  }
  stdout.writeln('Wrote ${_specs.length} files → ${dir.path}');
}

List<Map<String, dynamic>> get _specs => [
      _r(
        circuitId: 'albert_park',
        name: 'Albert Park Circuit',
        location: 'Melbourne, Australia',
        lengthM: 5278,
        laps: 58,
        d1: 260,
        since: 1996,
        contract: 2037,
        diff: 'Medium',
        oDiff: 'Medium',
        trackType: 'Temporary street circuit',
        dir: 'Clockwise',
        temp: 22,
        rain: 20,
        wind: 14,
        hum: 55,
        hpa: 1015,
        red: 15,
        vsc: 20,
        acc: 25,
        t1: 15,
        fastT: '1:19.813',
        fastD: 'Charles Leclerc',
        fastY: 2024,
        slowT: '1:35.000',
        slowD: 'Robert Kubica',
        slowY: 2019,
        avg: '1:23.000',
        top: 335,
        avgSp: 230,
        maxG: 4.8,
        avgG: 2.6,
        wear: 'Medium',
        strat: '2 stops',
        combo: 'Medium -> Hard -> Hard',
        pitS: 2.3,
        pitTeam: 'Ferrari',
        pitY: 2022,
        brake: 'Medium',
        harv: 'Low',
        zPct: 58,
        xPct: 42,
        mom: 8.5,
        smz: 5,
        momPts: 4,
        aeroTx: 28,
        mguK: 'High (14 braking zones)',
        dep: [
          'Sector 1 (main straight)',
          'Sector 2 (Lakeside)',
          'Sector 3 (final sector)',
        ],
        evo: 12,
        sun: '32 degrees (North-West)',
        vis: ['Turn 1', 'Turn 3'],
        msl: 12,
        elevCh: 8.0,
        q2425: '1:16.050',
        e26: '1:15.180',
        del: '-0.870',
        dTop: 12,
        eng: 'Mercedes-AMG',
        pod: {'Red Bull Racing': 55, 'Ferrari': 45, 'McLaren': 40},
        ftp: 69,
        kp: _kp(
          'albert_park',
          [
            (
              en:
                  '5 Straight Mode (Z-mode) zones with Active Aero transitions',
              nl: '5 Straight Mode (Z-mode) zones met Active Aero-transities',
            ),
            (
              en: 'Manual Override Mode (MOM) viable on long straights',
              nl: 'Manual Override Mode (MOM) bruikbaar op lange rechters',
            ),
            (
              en: 'Sweeping high-speed corners; variable temporary-surface grip',
              nl: 'Snelle vloeiende bochten; wisselende grip op tijdelijk asfalt',
            ),
            (
              en: 'Bumpy braking zones; 50/50 ICE/electric deployment discipline',
              nl: 'Hobbelige remzones; 50/50 ICE/elektrisch vermogensbeheer',
            ),
          ],
        ),
      ),
      _r(
        circuitId: 'shanghai',
        name: 'Shanghai International Circuit',
        location: 'Shanghai, China',
        lengthM: 5451,
        laps: 56,
        d1: 380,
        since: 2004,
        contract: 2027,
        diff: 'High',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 17,
        rain: 25,
        wind: 12,
        hum: 50,
        hpa: 1013,
        red: 7,
        vsc: 10,
        acc: 14,
        t1: 8,
        fastT: '1:32.238',
        fastD: 'Michael Schumacher',
        fastY: 2004,
        slowT: '1:45.000',
        slowD: 'Marcus Ericsson',
        slowY: 2018,
        avg: '1:35.000',
        top: 340,
        avgSp: 210,
        maxG: 4.5,
        avgG: 2.4,
        wear: 'Medium',
        strat: '1 stop',
        combo: 'Medium -> Hard',
        pitS: 2.2,
        pitTeam: 'Williams',
        pitY: 2019,
        brake: 'Medium',
        harv: 'Medium',
        zPct: 52,
        xPct: 48,
        mom: 7.8,
        smz: 4,
        momPts: 3,
        aeroTx: 22,
        mguK: 'Medium (12 braking zones)',
        dep: ['Back straight', 'Pit straight', 'Sector 3'],
        evo: 10,
        sun: '38 degrees (South-West)',
        vis: ['Turn 1', 'Turn 6'],
        msl: 15,
        elevCh: 12.0,
        q2425: '1:33.800',
        e26: '1:33.050',
        del: '-0.750',
        dTop: 10,
        eng: 'Mercedes-AMG',
        pod: {'Ferrari': 50, 'Red Bull Racing': 50, 'McLaren': 35},
        ftp: 62,
        kp: _kp('shanghai', [
          (
            en: 'Long back straight: high Z-mode / Straight Mode duty cycle',
            nl: 'Lang recht stuk: hoge Z-mode / Straight Mode-belasting',
          ),
          (
            en: 'Snail complex rewards precise MOM timing',
            nl: 'Slakkenhuis-complex beloont precieze MOM-timing',
          ),
          (
            en: 'Front-left tyre stress; rain probability elevated',
            nl: 'Linksvoor bandstress; verhoogde regenkans',
          ),
        ]),
      ),
      _r(
        circuitId: 'suzuka',
        name: 'Suzuka International Racing Course',
        location: 'Suzuka, Japan',
        lengthM: 5807,
        laps: 53,
        d1: 400,
        since: 1987,
        contract: 2029,
        diff: 'Very High',
        oDiff: 'High',
        trackType: 'Permanent road course',
        dir: 'Clockwise / figure-eight',
        temp: 19,
        rain: 30,
        wind: 16,
        hum: 60,
        hpa: 1018,
        red: 12,
        vsc: 18,
        acc: 22,
        t1: 15,
        fastT: '1:30.983',
        fastD: 'Lewis Hamilton',
        fastY: 2019,
        slowT: '1:40.000',
        slowD: 'Pierre Gasly',
        slowY: 2020,
        avg: '1:33.000',
        top: 330,
        avgSp: 230,
        maxG: 5.2,
        avgG: 3.1,
        wear: 'High',
        strat: '2 stops',
        combo: 'Soft -> Medium -> Hard',
        pitS: 2.1,
        pitTeam: 'Red Bull Racing',
        pitY: 2021,
        brake: 'High',
        harv: 'High',
        zPct: 48,
        xPct: 52,
        mom: 9.2,
        smz: 3,
        momPts: 5,
        aeroTx: 32,
        mguK: 'Very high (Degner, Hairpin, Casio)',
        dep: ['Sector 1', 'Sector 2', '130R run'],
        evo: 14,
        sun: '40 degrees (South)',
        vis: ['130R', 'Spoon'],
        msl: 45,
        elevCh: 40.0,
        q2425: '1:29.800',
        e26: '1:28.920',
        del: '-0.880',
        dTop: 9,
        eng: 'Honda RBPT',
        pod: {'Red Bull Racing': 70, 'McLaren': 45, 'Ferrari': 35},
        ftp: 58,
        kp: _kp('suzuka', [
          (
            en: 'High lateral G; Active Aero mode changes per sector rhythm',
            nl: 'Hoge laterale G; Active Aero-wissels op sectortempo',
          ),
          (
            en: '130R flat: Z-mode exit onto straight',
            nl: '130R flat: Z-mode naar recht stuk',
          ),
        ]),
      ),
      _r(
        circuitId: 'bahrain_sakhir',
        name: 'Bahrain International Circuit',
        location: 'Sakhir, Bahrain',
        lengthM: 5412,
        laps: 57,
        d1: 400,
        since: 2004,
        contract: 2036,
        diff: 'Medium',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 24,
        rain: 0,
        wind: 15,
        hum: 40,
        hpa: 1012,
        red: 5,
        vsc: 15,
        acc: 12,
        t1: 25,
        fastT: '1:31.447',
        fastD: 'Pedro de la Rosa',
        fastY: 2005,
        slowT: '1:35.000',
        slowD: 'Nikita Mazepin',
        slowY: 2021,
        avg: '1:33.500',
        top: 325,
        avgSp: 205,
        maxG: 4.2,
        avgG: 2.3,
        wear: 'High',
        strat: '2 stops',
        combo: 'Soft -> Hard -> Hard',
        pitS: 2.1,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'High',
        harv: 'Medium',
        zPct: 60,
        xPct: 40,
        mom: 8.0,
        smz: 6,
        momPts: 4,
        aeroTx: 26,
        mguK: 'High (desert traction + heavy braking)',
        dep: ['Main straight', 'Sector 2', 'Final complex'],
        evo: 18,
        sun: '42 degrees (West)',
        vis: ['Turn 1', 'Turn 4'],
        msl: 0,
        elevCh: 15.0,
        q2425: '1:30.200',
        e26: '1:29.350',
        del: '-0.850',
        dTop: 11,
        eng: 'Mercedes-AMG',
        pod: {'Red Bull Racing': 65, 'Ferrari': 40, 'McLaren': 30},
        ftp: 64,
        kp: _kp('bahrain_sakhir', [
          (
            en: 'Night race; long Straight Mode zones under lights',
            nl: 'Nachtrace; lange Straight Mode-stukken onder licht',
          ),
          (
            en: 'High tyre deg; 50/50 energy trim critical in traction',
            nl: 'Hoge bandendegradatie; 50/50-energie cruciaal in tractie',
          ),
        ]),
      ),
      _r(
        circuitId: 'jeddah',
        name: 'Jeddah Corniche Circuit',
        location: 'Jeddah, Saudi Arabia',
        lengthM: 6174,
        laps: 50,
        d1: 220,
        since: 2021,
        contract: 2030,
        diff: 'Very High',
        oDiff: 'Medium',
        trackType: 'Temporary street circuit',
        dir: 'Clockwise',
        temp: 27,
        rain: 0,
        wind: 10,
        hum: 60,
        hpa: 1010,
        red: 25,
        vsc: 35,
        acc: 40,
        t1: 10,
        fastT: '1:30.734',
        fastD: 'Lewis Hamilton',
        fastY: 2021,
        slowT: '1:34.000',
        slowD: 'Nicholas Latifi',
        slowY: 2022,
        avg: '1:32.000',
        top: 335,
        avgSp: 250,
        maxG: 4.9,
        avgG: 2.8,
        wear: 'Low',
        strat: '1 stop',
        combo: 'Medium -> Hard',
        pitS: 2.2,
        pitTeam: 'McLaren',
        pitY: 2023,
        brake: 'Medium',
        harv: 'Low',
        zPct: 62,
        xPct: 38,
        mom: 9.0,
        smz: 7,
        momPts: 5,
        aeroTx: 34,
        mguK: 'Medium (high average speed)',
        dep: ['Coastal straights', 'Sector 2', 'Sector 3'],
        evo: 8,
        sun: '18 degrees (West)',
        vis: ['Blind kinks', 'Turn 22'],
        msl: 5,
        elevCh: 18.0,
        q2425: '1:28.500',
        e26: '1:27.620',
        del: '-0.880',
        dTop: 13,
        eng: 'Honda RBPT',
        pod: {'Red Bull Racing': 60, 'McLaren': 40, 'Aston Martin': 25},
        ftp: 72,
        kp: _kp('jeddah', [
          (
            en: 'Fastest street layout; dense Active Aero transitions',
            nl: 'Snelste stratencircuit; dichte Active Aero-transities',
          ),
        ]),
      ),
      _r(
        circuitId: 'miami',
        name: 'Miami International Autodrome',
        location: 'Miami, USA',
        lengthM: 5412,
        laps: 57,
        d1: 200,
        since: 2022,
        contract: 2031,
        diff: 'Medium',
        oDiff: 'Medium',
        trackType: 'Temporary street circuit',
        dir: 'Clockwise',
        temp: 29,
        rain: 40,
        wind: 10,
        hum: 75,
        hpa: 1012,
        red: 10,
        vsc: 20,
        acc: 15,
        t1: 10,
        fastT: '1:29.708',
        fastD: 'Max Verstappen',
        fastY: 2023,
        slowT: '1:33.000',
        slowD: 'Kevin Magnussen',
        slowY: 2022,
        avg: '1:31.000',
        top: 335,
        avgSp: 215,
        maxG: 4.1,
        avgG: 2.2,
        wear: 'Medium',
        strat: '1 stop',
        combo: 'Medium -> Hard',
        pitS: 2.1,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'Medium',
        harv: 'Medium',
        zPct: 56,
        xPct: 44,
        mom: 7.5,
        smz: 4,
        momPts: 3,
        aeroTx: 20,
        mguK: 'Medium',
        dep: ['Long back straight', 'Sector 2'],
        evo: 11,
        sun: '55 degrees (West)',
        vis: ['Chicane complex'],
        msl: 2,
        elevCh: 6.0,
        q2425: '1:27.900',
        e26: '1:27.050',
        del: '-0.850',
        dTop: 10,
        eng: 'Mercedes-AMG',
        pod: {'McLaren': 55, 'Red Bull Racing': 45, 'Ferrari': 30},
        ftp: 66,
        kp: _kp('miami', [
          (
            en: 'Humidity + rain risk; slippery off-line',
            nl: 'Vochtigheid + regenrisico; glad naast de lijn',
          ),
        ]),
      ),
      _r(
        circuitId: 'montreal',
        name: 'Circuit Gilles-Villeneuve',
        location: 'Montreal, Canada',
        lengthM: 4361,
        laps: 70,
        d1: 260,
        since: 1978,
        contract: 2031,
        diff: 'Medium',
        oDiff: 'Medium',
        trackType: 'Temporary street circuit',
        dir: 'Clockwise',
        temp: 20,
        rain: 40,
        wind: 15,
        hum: 65,
        hpa: 1011,
        red: 20,
        vsc: 30,
        acc: 35,
        t1: 15,
        fastT: '1:13.078',
        fastD: 'Valtteri Bottas',
        fastY: 2019,
        slowT: '1:16.000',
        slowD: 'Lance Stroll',
        slowY: 2018,
        avg: '1:14.500',
        top: 340,
        avgSp: 210,
        maxG: 4.4,
        avgG: 2.1,
        wear: 'Low',
        strat: '2 stops',
        combo: 'Medium -> Hard -> Hard',
        pitS: 2.1,
        pitTeam: 'Williams',
        pitY: 2019,
        brake: 'High',
        harv: 'Medium',
        zPct: 54,
        xPct: 46,
        mom: 7.2,
        smz: 5,
        momPts: 4,
        aeroTx: 24,
        mguK: 'High (Wall of Champions zone)',
        dep: ['Casino straight', 'Senna curve'],
        evo: 15,
        sun: '48 degrees (West)',
        vis: ['Turn 1', 'Wall of Champions'],
        msl: 14,
        elevCh: 8.0,
        q2425: '1:12.400',
        e26: '1:11.580',
        del: '-0.820',
        dTop: 9,
        eng: 'Mercedes-AMG',
        pod: {'Red Bull Racing': 50, 'Ferrari': 35, 'McLaren': 35},
        ftp: 61,
        kp: _kp('montreal', [
          (
            en: 'Stop-and-go; heavy braking for chicanes',
            nl: 'Stop-and-go; zware remmen voor chicanes',
          ),
        ]),
      ),
      _r(
        circuitId: 'monaco',
        name: 'Circuit de Monaco',
        location: 'Monte Carlo, Monaco',
        lengthM: 3337,
        laps: 78,
        d1: 210,
        since: 1950,
        contract: 2027,
        diff: 'Very High',
        oDiff: 'Very High',
        trackType: 'Temporary street circuit',
        dir: 'Clockwise',
        temp: 23,
        rain: 10,
        wind: 8,
        hum: 55,
        hpa: 1016,
        red: 35,
        vsc: 45,
        acc: 50,
        t1: 40,
        fastT: '1:12.909',
        fastD: 'Lewis Hamilton',
        fastY: 2021,
        slowT: '1:18.000',
        slowD: 'Nikita Mazepin',
        slowY: 2021,
        avg: '1:15.000',
        top: 290,
        avgSp: 160,
        maxG: 3.6,
        avgG: 1.8,
        wear: 'Low',
        strat: '1 stop',
        combo: 'Medium -> Hard',
        pitS: 2.0,
        pitTeam: 'Red Bull Racing',
        pitY: 2021,
        brake: 'Low',
        harv: 'Low',
        zPct: 35,
        xPct: 65,
        mom: 6.0,
        smz: 2,
        momPts: 2,
        aeroTx: 18,
        mguK: 'Low (short bursts)',
        dep: ['Tunnel exit', 'Swimming pool'],
        evo: 20,
        sun: '52 degrees (South-West)',
        vis: ['Tunnel', 'Tabac'],
        msl: 47,
        elevCh: 42.0,
        q2425: '1:11.200',
        e26: '1:10.450',
        del: '-0.750',
        dTop: 6,
        eng: 'Ferrari',
        pod: {'Ferrari': 55, 'Red Bull Racing': 45, 'McLaren': 25},
        ftp: 48,
        kp: _kp('monaco', [
          (
            en: 'Minimal Straight Mode benefit; maximum X-mode precision',
            nl: 'Minimaal Straight Mode-voordeel; maximale X-mode precisie',
          ),
        ]),
      ),
      _r(
        circuitId: 'barcelona_catalunya',
        name: 'Circuit de Barcelona-Catalunya',
        location: 'Montmelo, Spain',
        lengthM: 4657,
        laps: 66,
        d1: 600,
        since: 1991,
        contract: 2026,
        diff: 'Medium',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 28,
        rain: 5,
        wind: 12,
        hum: 50,
        hpa: 1014,
        red: 5,
        vsc: 10,
        acc: 10,
        t1: 15,
        fastT: '1:16.330',
        fastD: 'Max Verstappen',
        fastY: 2023,
        slowT: '1:19.000',
        slowD: 'Logan Sargeant',
        slowY: 2023,
        avg: '1:18.000',
        top: 325,
        avgSp: 220,
        maxG: 4.7,
        avgG: 2.5,
        wear: 'High',
        strat: '2 stops',
        combo: 'Soft -> Medium -> Hard',
        pitS: 2.0,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'Medium',
        harv: 'High',
        zPct: 50,
        xPct: 50,
        mom: 8.2,
        smz: 4,
        momPts: 3,
        aeroTx: 26,
        mguK: 'High',
        dep: ['Main straight', 'Sector 3'],
        evo: 13,
        sun: '58 degrees (West)',
        vis: ['Turn 1', 'Final sector'],
        msl: 165,
        elevCh: 25.0,
        q2425: '1:13.100',
        e26: '1:12.280',
        del: '-0.820',
        dTop: 10,
        eng: 'Mercedes-AMG',
        pod: {'Red Bull Racing': 50, 'McLaren': 45, 'Ferrari': 40},
        ftp: 63,
        kp: _kp('barcelona_catalunya', [
          (
            en: 'Reference downforce test; tyre wear front-left',
            nl: 'Referentie downforce-test; bandenslijtage linksvoor',
          ),
        ]),
      ),
      _r(
        circuitId: 'spielberg',
        name: 'Red Bull Ring',
        location: 'Spielberg, Austria',
        lengthM: 4318,
        laps: 71,
        d1: 330,
        since: 1970,
        contract: 2030,
        diff: 'Low',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 24,
        rain: 30,
        wind: 10,
        hum: 55,
        hpa: 1015,
        red: 10,
        vsc: 25,
        acc: 15,
        t1: 20,
        fastT: '1:05.619',
        fastD: 'Carlos Sainz',
        fastY: 2020,
        slowT: '1:08.000',
        slowD: 'Nicholas Latifi',
        slowY: 2020,
        avg: '1:07.000',
        top: 330,
        avgSp: 235,
        maxG: 4.3,
        avgG: 2.4,
        wear: 'Medium',
        strat: '2 stops',
        combo: 'Medium -> Hard -> Medium',
        pitS: 2.1,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'Medium',
        harv: 'Medium',
        zPct: 57,
        xPct: 43,
        mom: 7.0,
        smz: 5,
        momPts: 3,
        aeroTx: 21,
        mguK: 'Medium (short lap)',
        dep: ['Start-finish', 'Rindt straight'],
        evo: 9,
        sun: '55 degrees (West)',
        vis: ['Turn 3', 'Turn 4'],
        msl: 660,
        elevCh: 65.0,
        q2425: '1:04.200',
        e26: '1:03.420',
        del: '-0.780',
        dTop: 11,
        eng: 'Honda RBPT',
        pod: {'Red Bull Racing': 75, 'Ferrari': 35, 'McLaren': 30},
        ftp: 68,
        kp: _kp('spielberg', [
          (
            en: 'Altitude reduces ICE margin; 50/50 hybrid balance sensitive',
            nl: 'Hoogte verkleint ICE-marge; 50/50 hybride gevoelig',
          ),
        ]),
      ),
      _r(
        circuitId: 'silverstone',
        name: 'Silverstone Circuit',
        location: 'Silverstone, UK',
        lengthM: 5891,
        laps: 52,
        d1: 280,
        since: 1950,
        contract: 2034,
        diff: 'High',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 20,
        rain: 50,
        wind: 20,
        hum: 65,
        hpa: 1010,
        red: 20,
        vsc: 25,
        acc: 30,
        t1: 15,
        fastT: '1:27.097',
        fastD: 'Max Verstappen',
        fastY: 2020,
        slowT: '1:31.000',
        slowD: 'Romain Grosjean',
        slowY: 2020,
        avg: '1:29.000',
        top: 330,
        avgSp: 245,
        maxG: 5.2,
        avgG: 2.9,
        wear: 'Very High',
        strat: '2 stops',
        combo: 'Medium -> Hard -> Soft',
        pitS: 2.2,
        pitTeam: 'McLaren',
        pitY: 2023,
        brake: 'High',
        harv: 'Very High',
        zPct: 52,
        xPct: 48,
        mom: 8.8,
        smz: 4,
        momPts: 4,
        aeroTx: 30,
        mguK: 'Very high (Maggots-Becketts)',
        dep: ['Hangar straight', 'Wellington straight'],
        evo: 16,
        sun: '50 degrees (South-West)',
        vis: ['Maggots', 'Copse'],
        msl: 153,
        elevCh: 35.0,
        q2425: '1:26.200',
        e26: '1:25.350',
        del: '-0.850',
        dTop: 10,
        eng: 'Mercedes-AMG',
        pod: {'McLaren': 50, 'Mercedes': 45, 'Red Bull Racing': 40},
        ftp: 66,
        kp: _kp('silverstone', [
          (
            en: 'High-speed flow; wind gusts affect Active Aero stability',
            nl: 'Hoge snelheid; windstoten beïnvloeden Active Aero-stabiliteit',
          ),
        ]),
      ),
      _r(
        circuitId: 'spa_francorchamps',
        name: 'Circuit de Spa-Francorchamps',
        location: 'Stavelot, Belgium',
        lengthM: 7004,
        laps: 44,
        d1: 270,
        since: 1950,
        contract: 2025,
        diff: 'High',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 18,
        rain: 60,
        wind: 15,
        hum: 75,
        hpa: 1009,
        red: 25,
        vsc: 35,
        acc: 40,
        t1: 30,
        fastT: '1:46.286',
        fastD: 'Valtteri Bottas',
        fastY: 2018,
        slowT: '1:50.000',
        slowD: 'Lance Stroll',
        slowY: 2018,
        avg: '1:48.000',
        top: 345,
        avgSp: 240,
        maxG: 4.8,
        avgG: 2.5,
        wear: 'Medium',
        strat: '2 stops',
        combo: 'Soft -> Medium -> Medium',
        pitS: 2.1,
        pitTeam: 'Williams',
        pitY: 2019,
        brake: 'High',
        harv: 'High',
        zPct: 55,
        xPct: 45,
        mom: 8.6,
        smz: 6,
        momPts: 4,
        aeroTx: 27,
        mguK: 'High (La Source, Bus Stop)',
        dep: ['Kemmel Straight', 'Sector 3'],
        evo: 22,
        sun: '48 degrees (South-West)',
        vis: ['Eau Rouge', 'Blanchimont'],
        msl: 410,
        elevCh: 102.0,
        q2425: '1:45.800',
        e26: '1:44.850',
        del: '-0.950',
        dTop: 14,
        eng: 'Mercedes-AMG',
        pod: {'Red Bull Racing': 55, 'Ferrari': 45, 'McLaren': 35},
        ftp: 70,
        kp: _kp('spa_francorchamps', [
          (
            en: 'Elevation + microclimate; longest lap on calendar',
            nl: 'Hoogte + microklima; langste ronde op de kalender',
          ),
        ]),
      ),
      _r(
        circuitId: 'hungaroring',
        name: 'Hungaroring',
        location: 'Mogyorod, Hungary',
        lengthM: 4381,
        laps: 70,
        d1: 610,
        since: 1986,
        contract: 2032,
        diff: 'High',
        oDiff: 'Very High',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 31,
        rain: 15,
        wind: 10,
        hum: 45,
        hpa: 1013,
        red: 10,
        vsc: 15,
        acc: 20,
        t1: 25,
        fastT: '1:16.627',
        fastD: 'Lewis Hamilton',
        fastY: 2020,
        slowT: '1:21.000',
        slowD: 'Nicholas Latifi',
        slowY: 2021,
        avg: '1:19.000',
        top: 315,
        avgSp: 200,
        maxG: 4.4,
        avgG: 2.2,
        wear: 'Medium',
        strat: '2 stops',
        combo: 'Medium -> Hard -> Hard',
        pitS: 2.3,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'Medium',
        harv: 'High',
        zPct: 42,
        xPct: 58,
        mom: 7.4,
        smz: 3,
        momPts: 3,
        aeroTx: 25,
        mguK: 'High (stop-start)',
        dep: ['Sector 2', 'Main straight'],
        evo: 14,
        sun: '60 degrees (West)',
        vis: ['Turn 2', 'Turn 4'],
        msl: 210,
        elevCh: 35.0,
        q2425: '1:17.500',
        e26: '1:16.720',
        del: '-0.780',
        dTop: 8,
        eng: 'Mercedes-AMG',
        pod: {'McLaren': 45, 'Red Bull Racing': 40, 'Mercedes': 35},
        ftp: 55,
        kp: _kp('hungaroring', [
          (
            en: 'Overtaking difficult; traction exits dominate energy use',
            nl: 'Moeilijk inhalen; tractie-exits domineren energieverbruik',
          ),
        ]),
      ),
      _r(
        circuitId: 'zandvoort',
        name: 'Circuit Zandvoort',
        location: 'Zandvoort, Netherlands',
        lengthM: 4259,
        laps: 72,
        d1: 240,
        since: 1952,
        contract: 2025,
        diff: 'High',
        oDiff: 'Very High',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 20,
        rain: 45,
        wind: 25,
        hum: 70,
        hpa: 1012,
        red: 15,
        vsc: 25,
        acc: 25,
        t1: 15,
        fastT: '1:11.097',
        fastD: 'Lewis Hamilton',
        fastY: 2021,
        slowT: '1:15.000',
        slowD: 'Nikita Mazepin',
        slowY: 2021,
        avg: '1:13.000',
        top: 320,
        avgSp: 215,
        maxG: 4.9,
        avgG: 2.6,
        wear: 'High',
        strat: '2 stops',
        combo: 'Soft -> Medium -> Hard',
        pitS: 2.2,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'High',
        harv: 'High',
        zPct: 48,
        xPct: 52,
        mom: 8.4,
        smz: 3,
        momPts: 4,
        aeroTx: 29,
        mguK: 'High (banked corners)',
        dep: ['Start-finish', 'Sector 2'],
        evo: 17,
        sun: '42 degrees (South-West)',
        vis: ['Tarzan', 'Hugenholtz'],
        msl: 3,
        elevCh: 12.0,
        q2425: '1:10.200',
        e26: '1:09.380',
        del: '-0.820',
        dTop: 9,
        eng: 'Honda RBPT',
        pod: {'Red Bull Racing': 70, 'McLaren': 40, 'Ferrari': 25},
        ftp: 60,
        kp: _kp('zandvoort', [
          (
            en: 'Banked turns; North Sea wind shifts aero balance',
            nl: 'Hellende bochten; Noordzeewind verschuift aerobalans',
          ),
        ]),
      ),
      _r(
        circuitId: 'monza',
        name: 'Autodromo Nazionale Monza',
        location: 'Monza, Italy',
        lengthM: 5793,
        laps: 53,
        d1: 640,
        since: 1950,
        contract: 2025,
        diff: 'Low',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 26,
        rain: 10,
        wind: 5,
        hum: 45,
        hpa: 1015,
        red: 10,
        vsc: 15,
        acc: 20,
        t1: 40,
        fastT: '1:21.046',
        fastD: 'Rubens Barrichello',
        fastY: 2004,
        slowT: '1:25.000',
        slowD: 'Logan Sargeant',
        slowY: 2023,
        avg: '1:23.000',
        top: 360,
        avgSp: 260,
        maxG: 3.8,
        avgG: 1.9,
        wear: 'Low',
        strat: '1 stop',
        combo: 'Medium -> Hard',
        pitS: 2.1,
        pitTeam: 'Ferrari',
        pitY: 2022,
        brake: 'Low',
        harv: 'Low',
        zPct: 68,
        xPct: 32,
        mom: 7.0,
        smz: 6,
        momPts: 3,
        aeroTx: 20,
        mguK: 'Low (few heavy stops)',
        dep: ['Main straight', 'Curva Grande'],
        evo: 8,
        sun: '52 degrees (West)',
        vis: ['Turn 1', 'Ascari'],
        msl: 180,
        elevCh: 25.0,
        q2425: '1:20.400',
        e26: '1:19.520',
        del: '-0.880',
        dTop: 15,
        eng: 'Ferrari',
        pod: {'Ferrari': 60, 'Red Bull Racing': 40, 'McLaren': 30},
        ftp: 78,
        kp: _kp('monza', [
          (
            en: 'Temple of Speed: maximum Straight Mode duty',
            nl: 'Temple of Speed: maximale Straight Mode-belasting',
          ),
        ]),
      ),
      _r(
        circuitId: 'madrid_madring',
        name: 'Circuito de Madring',
        location: 'Madrid, Spain',
        lengthM: 5474,
        laps: 54,
        d1: 300,
        since: 2026,
        contract: 2035,
        diff: 'High',
        oDiff: 'Medium',
        trackType: 'Hybrid street / permanent',
        dir: 'Clockwise',
        temp: 27,
        rain: 10,
        wind: 10,
        hum: 45,
        hpa: 1016,
        red: 25,
        vsc: 35,
        acc: 30,
        t1: 20,
        fastT: 'TBD',
        fastD: 'TBD',
        fastY: 2026,
        slowT: 'TBD',
        slowD: 'TBD',
        slowY: 2026,
        avg: '1:34.000',
        top: 320,
        avgSp: 215,
        maxG: 4.2,
        avgG: 2.4,
        wear: 'Medium',
        strat: '2 stops',
        combo: 'Soft -> Medium -> Hard',
        pitS: 2.2,
        pitTeam: 'TBD',
        pitY: 2026,
        brake: 'Medium',
        harv: 'Medium',
        zPct: 52,
        xPct: 48,
        mom: 8.0,
        smz: 4,
        momPts: 3,
        aeroTx: 24,
        mguK: 'Medium (preliminary layout)',
        dep: ['Main straight', 'IFEMA sector', 'Sector 3'],
        evo: 25,
        sun: '56 degrees (West)',
        vis: ['Tunnel exits', 'Turn 1'],
        msl: 650,
        elevCh: 45.0,
        q2425: '1:35.200',
        e26: '1:34.100',
        del: '-1.100',
        dTop: 11,
        eng: 'Mercedes-AMG',
        pod: {'Red Bull Racing': 40, 'Ferrari': 35, 'McLaren': 35},
        ftp: 60,
        kp: _kp('madrid_madring', [
          (
            en: 'New venue 2026; provisional energy and aero targets',
            nl: 'Nieuw circuit 2026; voorlopige energie- en aerodoelen',
          ),
        ]),
      ),
      _r(
        circuitId: 'baku',
        name: 'Baku City Circuit',
        location: 'Baku, Azerbaijan',
        lengthM: 6003,
        laps: 51,
        d1: 200,
        since: 2016,
        contract: 2026,
        diff: 'Very High',
        oDiff: 'Medium',
        trackType: 'Temporary street circuit',
        dir: 'Anti-clockwise',
        temp: 24,
        rain: 5,
        wind: 22,
        hum: 55,
        hpa: 1016,
        red: 30,
        vsc: 40,
        acc: 45,
        t1: 20,
        fastT: '1:43.009',
        fastD: 'Charles Leclerc',
        fastY: 2019,
        slowT: '1:47.000',
        slowD: 'Lance Stroll',
        slowY: 2021,
        avg: '1:45.000',
        top: 350,
        avgSp: 210,
        maxG: 4.0,
        avgG: 2.0,
        wear: 'Low',
        strat: '1 stop',
        combo: 'Medium -> Hard',
        pitS: 1.9,
        pitTeam: 'Williams',
        pitY: 2016,
        brake: 'Medium',
        harv: 'Low',
        zPct: 58,
        xPct: 42,
        mom: 8.2,
        smz: 6,
        momPts: 4,
        aeroTx: 26,
        mguK: 'Medium (castle section)',
        dep: ['Main straight', 'Coastal section'],
        evo: 10,
        sun: '62 degrees (West)',
        vis: ['Castle', 'Turn 8'],
        msl: -28,
        elevCh: 12.0,
        q2425: '1:41.800',
        e26: '1:40.850',
        del: '-0.950',
        dTop: 12,
        eng: 'Ferrari',
        pod: {'McLaren': 45, 'Ferrari': 40, 'Red Bull Racing': 35},
        ftp: 68,
        kp: _kp('baku', [
          (
            en: 'Caspian wind; narrow castle: MOM discipline',
            nl: 'Kaspische wind; smal kasteel: MOM-discipline',
          ),
        ]),
      ),
      _r(
        circuitId: 'marina_bay',
        name: 'Marina Bay Street Circuit',
        location: 'Singapore',
        lengthM: 4940,
        laps: 62,
        d1: 300,
        since: 2008,
        contract: 2028,
        diff: 'Very High',
        oDiff: 'Very High',
        trackType: 'Temporary street circuit',
        dir: 'Anti-clockwise',
        temp: 31,
        rain: 50,
        wind: 10,
        hum: 85,
        hpa: 1008,
        red: 25,
        vsc: 60,
        acc: 50,
        t1: 15,
        fastT: '1:34.486',
        fastD: 'Daniel Ricciardo',
        fastY: 2024,
        slowT: '1:39.000',
        slowD: 'Logan Sargeant',
        slowY: 2023,
        avg: '1:37.000',
        top: 310,
        avgSp: 175,
        maxG: 4.2,
        avgG: 2.1,
        wear: 'High',
        strat: '2 stops',
        combo: 'Medium -> Hard -> Hard',
        pitS: 2.3,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'High',
        harv: 'High',
        zPct: 44,
        xPct: 56,
        mom: 7.8,
        smz: 3,
        momPts: 4,
        aeroTx: 27,
        mguK: 'High (23 corners)',
        dep: ['Raffles straight', 'Sector 3'],
        evo: 19,
        sun: '28 degrees (West)',
        vis: ['Anderson Bridge', 'Turn 13'],
        msl: 5,
        elevCh: 18.0,
        q2425: '1:32.400',
        e26: '1:31.520',
        del: '-0.880',
        dTop: 8,
        eng: 'Mercedes-AMG',
        pod: {'McLaren': 50, 'Ferrari': 35, 'Red Bull Racing': 30},
        ftp: 52,
        kp: _kp('marina_bay', [
          (
            en: 'Night humidity; battery thermal limits with 50/50 split',
            nl: 'Nachtvochtigheid; batterijthermiek met 50/50-split',
          ),
        ]),
      ),
      _r(
        circuitId: 'cota',
        name: 'Circuit of The Americas',
        location: 'Austin, USA',
        lengthM: 5513,
        laps: 56,
        d1: 280,
        since: 2012,
        contract: 2026,
        diff: 'High',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Anti-clockwise',
        temp: 28,
        rain: 10,
        wind: 15,
        hum: 45,
        hpa: 1013,
        red: 10,
        vsc: 20,
        acc: 25,
        t1: 30,
        fastT: '1:36.169',
        fastD: 'Charles Leclerc',
        fastY: 2019,
        slowT: '1:40.000',
        slowD: 'Nikita Mazepin',
        slowY: 2021,
        avg: '1:38.000',
        top: 335,
        avgSp: 205,
        maxG: 4.5,
        avgG: 2.5,
        wear: 'High',
        strat: '2 stops',
        combo: 'Medium -> Hard -> Medium',
        pitS: 2.2,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'High',
        harv: 'High',
        zPct: 53,
        xPct: 47,
        mom: 8.0,
        smz: 5,
        momPts: 4,
        aeroTx: 25,
        mguK: 'High (Turn 1 hill)',
        dep: ['Back straight', 'Sector 1'],
        evo: 13,
        sun: '35 degrees (South-West)',
        vis: ['Turn 1', 'Esses'],
        msl: 150,
        elevCh: 40.0,
        q2425: '1:35.200',
        e26: '1:34.350',
        del: '-0.850',
        dTop: 10,
        eng: 'Honda RBPT',
        pod: {'Red Bull Racing': 55, 'Ferrari': 45, 'McLaren': 35},
        ftp: 64,
        kp: _kp('cota', [
          (
            en: 'Elevation change; bumpy surface under braking',
            nl: 'Hoogteverschil; hobbelig asfalt bij remmen',
          ),
        ]),
      ),
      _r(
        circuitId: 'mexico_city',
        name: 'Autodromo Hermanos Rodriguez',
        location: 'Mexico City, Mexico',
        lengthM: 4304,
        laps: 71,
        d1: 810,
        since: 1962,
        contract: 2025,
        diff: 'Medium',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 23,
        rain: 20,
        wind: 8,
        hum: 40,
        hpa: 1025,
        red: 15,
        vsc: 25,
        acc: 20,
        t1: 35,
        fastT: '1:17.774',
        fastD: 'Valtteri Bottas',
        fastY: 2021,
        slowT: '1:21.000',
        slowD: 'Nicholas Latifi',
        slowY: 2021,
        avg: '1:19.000',
        top: 350,
        avgSp: 195,
        maxG: 4.1,
        avgG: 2.0,
        wear: 'Medium',
        strat: '1 stop',
        combo: 'Medium -> Hard',
        pitS: 2.0,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'Medium',
        harv: 'Medium',
        zPct: 56,
        xPct: 44,
        mom: 7.2,
        smz: 5,
        momPts: 3,
        aeroTx: 22,
        mguK: 'Medium (thin air)',
        dep: ['Main straight', 'Stadium section'],
        evo: 12,
        sun: '38 degrees (South-West)',
        vis: ['Stadium', 'Turn 1'],
        msl: 2240,
        elevCh: 45.0,
        q2425: '1:17.900',
        e26: '1:17.050',
        del: '-0.850',
        dTop: 9,
        eng: 'Honda RBPT',
        pod: {'Red Bull Racing': 65, 'Ferrari': 35, 'Mercedes': 30},
        ftp: 67,
        kp: _kp('mexico_city', [
          (
            en: 'Altitude reduces drag; cooling and 50/50 deployment sensitive',
            nl: 'Hoogte vermindert weerstand; koeling en 50/50 gevoelig',
          ),
        ]),
      ),
      _r(
        circuitId: 'interlagos',
        name: 'Autodromo Jose Carlos Pace',
        location: 'Sao Paulo, Brazil',
        lengthM: 4309,
        laps: 71,
        d1: 190,
        since: 1973,
        contract: 2030,
        diff: 'High',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Anti-clockwise',
        temp: 25,
        rain: 60,
        wind: 12,
        hum: 65,
        hpa: 1012,
        red: 20,
        vsc: 35,
        acc: 30,
        t1: 25,
        fastT: '1:10.540',
        fastD: 'Valtteri Bottas',
        fastY: 2018,
        slowT: '1:14.000',
        slowD: 'Logan Sargeant',
        slowY: 2023,
        avg: '1:12.500',
        top: 335,
        avgSp: 215,
        maxG: 4.6,
        avgG: 2.5,
        wear: 'Medium',
        strat: '2 stops',
        combo: 'Soft -> Medium -> Medium',
        pitS: 1.8,
        pitTeam: 'Red Bull Racing',
        pitY: 2019,
        brake: 'High',
        harv: 'High',
        zPct: 50,
        xPct: 50,
        mom: 8.0,
        smz: 4,
        momPts: 4,
        aeroTx: 26,
        mguK: 'High (Senna S)',
        dep: ['Reta Oposta', 'Sector 3'],
        evo: 18,
        sun: '72 degrees (North-West)',
        vis: ['Senna S', 'Descida do Lago'],
        msl: 800,
        elevCh: 44.0,
        q2425: '1:10.900',
        e26: '1:10.050',
        del: '-0.850',
        dTop: 10,
        eng: 'Honda RBPT',
        pod: {'Red Bull Racing': 60, 'McLaren': 35, 'Ferrari': 30},
        ftp: 62,
        kp: _kp('interlagos', [
          (
            en: 'Anti-clockwise; rain probability; passionate crowd',
            nl: 'Tegen de klok in; regenkans; fanatiek publiek',
          ),
        ]),
      ),
      _r(
        circuitId: 'las_vegas',
        name: 'Las Vegas Street Circuit',
        location: 'Las Vegas, USA',
        lengthM: 6201,
        laps: 50,
        d1: 240,
        since: 2023,
        contract: 2032,
        diff: 'Medium',
        oDiff: 'Medium',
        trackType: 'Temporary street circuit',
        dir: 'Clockwise',
        temp: 12,
        rain: 0,
        wind: 10,
        hum: 30,
        hpa: 1018,
        red: 15,
        vsc: 30,
        acc: 35,
        t1: 25,
        fastT: '1:35.490',
        fastD: 'Oscar Piastri',
        fastY: 2023,
        slowT: '1:39.000',
        slowD: 'Kevin Magnussen',
        slowY: 2023,
        avg: '1:37.000',
        top: 350,
        avgSp: 235,
        maxG: 3.9,
        avgG: 2.1,
        wear: 'Medium',
        strat: '1 stop',
        combo: 'Medium -> Hard',
        pitS: 2.2,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'High',
        harv: 'Low',
        zPct: 64,
        xPct: 36,
        mom: 7.5,
        smz: 7,
        momPts: 4,
        aeroTx: 24,
        mguK: 'Low (long straights, cold track)',
        dep: ['The Strip', 'Sphere sector'],
        evo: 9,
        sun: '22 degrees (South)',
        vis: ['Strip braking zones'],
        msl: 610,
        elevCh: 35.0,
        q2425: '1:34.200',
        e26: '1:33.250',
        del: '-0.950',
        dTop: 14,
        eng: 'Honda RBPT',
        pod: {'Red Bull Racing': 55, 'Ferrari': 35, 'McLaren': 35},
        ftp: 71,
        kp: _kp('las_vegas', [
          (
            en: 'Cold night track; low grip; long Straight Mode sections',
            nl: 'Koude nachtbaan; lage grip; lange Straight Mode-stukken',
          ),
        ]),
      ),
      _r(
        circuitId: 'lusail',
        name: 'Losail International Circuit',
        location: 'Lusail, Qatar',
        lengthM: 5419,
        laps: 57,
        d1: 350,
        since: 2021,
        contract: 2032,
        diff: 'High',
        oDiff: 'High',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 28,
        rain: 0,
        wind: 18,
        hum: 55,
        hpa: 1013,
        red: 5,
        vsc: 15,
        acc: 15,
        t1: 10,
        fastT: '1:23.196',
        fastD: 'Max Verstappen',
        fastY: 2021,
        slowT: '1:27.000',
        slowD: 'Logan Sargeant',
        slowY: 2023,
        avg: '1:25.000',
        top: 330,
        avgSp: 235,
        maxG: 5.3,
        avgG: 3.0,
        wear: 'Very High',
        strat: '3 stops',
        combo: 'Medium -> Medium -> Hard -> Soft',
        pitS: 1.8,
        pitTeam: 'McLaren',
        pitY: 2023,
        brake: 'Very High',
        harv: 'Very High',
        zPct: 49,
        xPct: 51,
        mom: 9.0,
        smz: 4,
        momPts: 5,
        aeroTx: 31,
        mguK: 'Very high (high-speed sequence)',
        dep: ['Main straight', 'Sector 2'],
        evo: 16,
        sun: '18 degrees (West)',
        vis: ['Turn 6', 'Turn 10'],
        msl: 5,
        elevCh: 12.0,
        q2425: '1:23.800',
        e26: '1:22.850',
        del: '-0.950',
        dTop: 9,
        eng: 'Mercedes-AMG',
        pod: {'Red Bull Racing': 65, 'McLaren': 40, 'Ferrari': 25},
        ftp: 59,
        kp: _kp('lusail', [
          (
            en: 'Tyre stress; night heat; sustained lateral load',
            nl: 'Bandenstress; nachtwarmte; aanhoudende laterale belasting',
          ),
        ]),
      ),
      _r(
        circuitId: 'yas_marina',
        name: 'Yas Marina Circuit',
        location: 'Abu Dhabi, UAE',
        lengthM: 5281,
        laps: 58,
        d1: 300,
        since: 2009,
        contract: 2030,
        diff: 'Medium',
        oDiff: 'Medium',
        trackType: 'Permanent road course',
        dir: 'Clockwise',
        temp: 26,
        rain: 0,
        wind: 12,
        hum: 50,
        hpa: 1015,
        red: 5,
        vsc: 10,
        acc: 10,
        t1: 15,
        fastT: '1:26.103',
        fastD: 'Max Verstappen',
        fastY: 2021,
        slowT: '1:30.000',
        slowD: 'Nikita Mazepin',
        slowY: 2021,
        avg: '1:28.000',
        top: 335,
        avgSp: 215,
        maxG: 4.5,
        avgG: 2.3,
        wear: 'Medium',
        strat: '1 stop',
        combo: 'Medium -> Hard',
        pitS: 2.1,
        pitTeam: 'Red Bull Racing',
        pitY: 2023,
        brake: 'Medium',
        harv: 'Medium',
        zPct: 56,
        xPct: 44,
        mom: 7.8,
        smz: 5,
        momPts: 3,
        aeroTx: 24,
        mguK: 'Medium',
        dep: ['Main straight', 'Hotel section'],
        evo: 11,
        sun: '15 degrees (South-West)',
        vis: ['Marina section', 'Turn 9'],
        msl: 2,
        elevCh: 10.0,
        q2425: '1:24.200',
        e26: '1:23.350',
        del: '-0.850',
        dTop: 11,
        eng: 'Honda RBPT',
        pod: {'Red Bull Racing': 60, 'Ferrari': 35, 'Mercedes': 30},
        ftp: 65,
        kp: _kp('yas_marina', [
          (
            en: 'Twilight finale; traction exits in sector 3',
            nl: 'Schemerfinale; tractie-exits in sector 3',
          ),
        ]),
      ),
    ];

List<Map<String, dynamic>> _kp(String id, List<({String en, String nl})> lines) {
  return List<Map<String, dynamic>>.generate(
    lines.length,
    (i) => {
      'l10n_key': 'circuits.$id.key_point_$i',
      'strings': {'en': lines[i].en, 'nl': lines[i].nl},
    },
  );
}

Map<String, dynamic> _r({
  required String circuitId,
  required String name,
  required String location,
  required int lengthM,
  required int laps,
  required int d1,
  required int since,
  required int contract,
  required String diff,
  required String oDiff,
  required String trackType,
  required String dir,
  required int temp,
  required int rain,
  required int wind,
  required int hum,
  required int hpa,
  required int red,
  required int vsc,
  required int acc,
  required int t1,
  required String fastT,
  required String fastD,
  required int fastY,
  required String slowT,
  required String slowD,
  required int slowY,
  required String avg,
  required int top,
  required int avgSp,
  required double maxG,
  required double avgG,
  required String wear,
  required String strat,
  required String combo,
  required double pitS,
  required String pitTeam,
  required int pitY,
  required String brake,
  required String harv,
  required int zPct,
  required int xPct,
  required double mom,
  required int smz,
  required int momPts,
  required int aeroTx,
  required String mguK,
  required List<String> dep,
  required int evo,
  required String sun,
  required List<String> vis,
  required int msl,
  required double elevCh,
  required String q2425,
  required String e26,
  required String del,
  required int dTop,
  required String eng,
  required Map<String, int> pod,
  required int ftp,
  required List<Map<String, dynamic>> kp,
}) {
  final sc = (acc + vsc + 12).clamp(30, 92);
  return {
    'meta': {
      'path': '/data/circuits/$circuitId.json',
      'season': 2026,
      'regulation_notes':
          'DRS terminology removed; use Straight Mode (Z-mode) and Manual Override Mode (MOM). Active Aero 2026. Electrical/ICE power split 50/50 for stated energy metrics.',
    },
    'circuit_id': circuitId,
    'name': name,
    'location': location,
    'circuit_info': {
      'length_m': lengthM,
      'laps': laps,
      'distance_to_turn_1_m': d1,
      'on_calendar_since': since,
      'contract_until': contract,
      'circuit_difficulty': {
        'l10n_key': 'circuit.difficulty.${diff.toLowerCase().replaceAll(' ', '_')}',
        'strings': {'en': diff, 'nl': _diffNl(diff)},
      },
      'overtaking_difficulty': {
        'l10n_key':
            'circuit.overtaking.${oDiff.toLowerCase().replaceAll(' ', '_')}',
        'strings': {'en': oDiff, 'nl': _diffNl(oDiff)},
      },
      'track_type': {
        'l10n_key': 'circuit.track_type.$circuitId',
        'strings': {'en': trackType, 'nl': trackType},
      },
      'direction': {
        'l10n_key': 'circuit.direction.${dir.toLowerCase().replaceAll(' ', '_').replaceAll('/', '_')}',
        'strings': {'en': dir, 'nl': dir},
      },
    },
    'weather_forecast': {
      'temperature_c': temp,
      'rain_chance_pct': rain,
      'wind_speed_kmh': wind,
      'humidity_pct': hum,
      'air_pressure_hpa': hpa,
    },
    'risks_and_incidents': {
      'red_flag_chance_pct': red,
      'vsc_chance_pct': vsc,
      'accident_chance_pct': acc,
      'turn_1_accident_chance_pct': t1,
      'safety_car_probability_pct': sc,
    },
    'lap_and_speed_stats': {
      'fastest_lap_record': {'time': fastT, 'driver': fastD, 'year': fastY},
      'slowest_lap_historical': {'time': slowT, 'driver': slowD, 'year': slowY},
      'average_lap_time': avg,
      'top_speed_kmh': top,
      'average_speed_kmh': avgSp,
      'max_g_force': maxG,
      'avg_g_force': avgG,
    },
    'tyres_and_strategy': {
      'tire_wear': {
        'l10n_key': 'tyre.wear.${wear.toLowerCase().replaceAll(' ', '_')}',
        'strings': {'en': wear, 'nl': wear},
      },
      'strategy_typical': {
        'l10n_key': 'strategy.$circuitId.typical',
        'strings': {'en': strat, 'nl': strat},
      },
      'best_combination': {
        'l10n_key': 'strategy.$circuitId.combo',
        'strings': {'en': combo, 'nl': combo},
      },
      'fastest_pitstop_record': {
        'time_s': pitS,
        'team': pitTeam,
        'year': pitY,
      },
      'braking_intensity': {
        'l10n_key': 'tyre.braking.$circuitId',
        'strings': {'en': brake, 'nl': brake},
      },
      'harvesting_difficulty': {
        'l10n_key': 'energy.harvest.$circuitId',
        'strings': {'en': harv, 'nl': harv},
      },
    },
    'aerodynamics_2026': {
      'x_mode_usage_pct': xPct,
      'z_mode_usage_pct': zPct,
      'manual_override_impact_score': mom,
      'straight_mode_zones': smz,
      'manual_override_activation_points': momPts,
      'active_aero_transitions_per_lap': aeroTx,
    },
    'energy_management': {
      'electrical_power_ratio_pct': 50,
      'ice_power_ratio_pct': 50,
      'mgu_k_recovery_points': {
        'l10n_key': 'energy.mguk.$circuitId',
        'strings': {'en': mguK, 'nl': mguK},
      },
      'primary_deployment_sectors': [
        for (var i = 0; i < dep.length; i++)
          {
            'l10n_key': 'energy.deploy.$circuitId.$i',
            'strings': {'en': dep[i], 'nl': dep[i]},
          },
      ],
    },
    'ambient_conditions': {
      'track_evolution_factor_pct': evo,
      'sun_angle_at_race_start': {
        'l10n_key': 'ambient.sun.$circuitId',
        'strings': {'en': sun, 'nl': sun},
      },
      'visibility_risk_sectors': vis,
      'elevation_above_sea_level_m': msl,
      'max_elevation_change_m': elevCh,
    },
    'era_comparison': {
      'avg_lap_time_2024_2025_qual_reference': q2425,
      'est_lap_time_2026': e26,
      'delta_seconds': del,
      'top_speed_increase_kmh': dTop,
      'methodology_note': {
        'l10n_key': 'era.methodology.2026',
        'strings': {
          'en':
              'Estimated from 2024/2025 qualifying reference; adjusted for -30 kg mass and active aero top-speed gain (indicative, not official).',
          'nl':
              'Geschat t.o.v. kwalificatie 2024/2025; correctie voor -30 kg en active aero topsnelheid (indicatief).',
        },
      },
    },
    'historical_success_rate': {
      'most_reliable_engine_supplier': eng,
      'team_podium_percentage_last_5_years': pod,
    },
    'circuit_characteristics': {
      'key_points': kp,
      'full_throttle_pct': ftp,
    },
  };
}

String _diffNl(String e) {
  return switch (e) {
    'Medium' => 'Gemiddeld',
    'High' => 'Hoog',
    'Low' => 'Laag',
    'Very High' => 'Zeer hoog',
    'Very Low' => 'Zeer laag',
    _ => e,
  };
}
