// Regenerates lib/circuit_detail/circuit_l10n_resolver.dart from app_localizations getters.
// Run: dart run tool/write_circuit_l10n_resolver.dart

import 'dart:io';

void main() {
  final src = File('lib/l10n/app_localizations.dart').readAsStringSync();
  final re = RegExp(
    r'String get (cat_\w+|type_\w+|dir_\w+|diff_\w+|feature_\w+|sun_\w+|circuit_difficulty_l10n|overtaking_difficulty_l10n|recommended_strategy_l10n|best_tyre_combination|cfield_\w+);',
  );
  final keys =
      re.allMatches(src).map((m) => m.group(1)!).toSet().toList()..sort();

  final buf = StringBuffer()
    ..writeln(
      "// Generated by tool/write_circuit_l10n_resolver.dart — do not edit by hand.",
    )
    ..writeln()
    ..writeln("import 'package:f1/l10n/app_localizations.dart';")
    ..writeln()
    ..writeln('/// Returns a localized string when [key] matches an ARB circuit-related entry.')
    ..writeln('String? circuitL10nOrNull(AppLocalizations l10n, String key) {')
    ..writeln('  return switch (key) {');

  for (final k in keys) {
    buf.writeln("    '$k' => l10n.$k,");
  }
  buf
    ..writeln('    _ => null,')
    ..writeln('  };')
    ..writeln('}')
    ..writeln()
    ..writeln(
      '/// Resolves known l10n keys; otherwise formats snake_case for display.',
    )
    ..writeln(
      'String circuitLocalizedString(AppLocalizations l10n, String key) {',
    )
    ..writeln(
      '  return circuitL10nOrNull(l10n, key) ??',
    )
    ..writeln(
      "      circuitL10nOrNull(l10n, 'sun_\$key') ??",
    )
    ..writeln(
      "      circuitL10nOrNull(l10n, 'cfield_\$key') ??",
    )
    ..writeln('      humanizeDataLabel(key);')
    ..writeln('}')
    ..writeln()
    ..writeln('/// Turns `track_type_l10n` / `max_g_force` into readable labels.')
    ..writeln('String humanizeDataLabel(String key) {')
    ..writeln("  var k = key;")
    ..writeln("  if (k.endsWith('_l10n')) {")
    ..writeln('    k = k.substring(0, k.length - 5);')
    ..writeln('  }')
    ..writeln(r"  if (!k.contains('_')) return k;")
    ..writeln("  return k.split('_').map((w) {")
    ..writeln('    if (w.isEmpty) return w;')
    ..writeln('    final lower = w.toLowerCase();')
    ..writeln(
      '    return lower[0].toUpperCase() + lower.substring(1);',
    )
    ..writeln("  }).join(' ');")
    ..writeln('}');

  final out = File('lib/circuit_detail/circuit_l10n_resolver.dart');
  out.parent.createSync(recursive: true);
  out.writeAsStringSync(buf.toString());
  stdout.writeln('Wrote ${out.path} (${keys.length} keys)');
}
