name: F1 Data Fetcher & Deploy

on:
  schedule:
    - cron: '0 * * * 5,6,0'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Fetch Script
        run: dart fetch_session_data.dart

      - name: Commit and Push Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated F1 data update" || echo "No changes to commit"
          git push origin main

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/F1-Info/"

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    needs: run-script
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4